### ISSUE TITLE
Implement exact phrase matching

### ISSUE THREAD

**Issue by bglw** [CloudCannon/pagefind#10]
Pagefind has the data required to provide an "exact phrase" search functionality a-la-Goog, where the term is provided in quotes.

**Comment by j2kun** [comment]
I am surprised to see this marked completed because I can't seem to get this to work today... Is this feature officially supported?

**Comment by bglw** [comment]
Hey @j2kun 👋 

Do you have an example where this isn't working? 

It is supported, though with the requirement that the entire search term is quoted:

```diff
# this will match the exact phrase
"static search"

# this will not, and is equivalent to searching `static search tool` unquoted.
"static search" tool
```

If you go to https://pagefind.app/ and search for `static search` vs `"static search"` you should see the exact matching in action.
