### ISSUE TITLE
Windows 11: npx pagefind --source public - Not Working

### ISSUE THREAD

**Issue by RenaudDev** [CloudCannon/pagefind#100]
Hi, very exciting project!

Trying to install on a hugo website and nothing is happening.

I made a build a my website
`hugo`

I installed it:
`npx pagefind --source "public"`

I created a pagefind.yml in the root directory

```
# pagefind.yml
source: public
bundle_dir: _pagefind
```
Then when I type
`npx pagefind`

After a couple seconds...nothing happens.

I tried installing it via npm and then run
`npm run`

Nothing happens there either.

**Comment by RenaudDev** [comment]
Hi, 

so afterall, I installed the version 0.6.1 and everything seems to work fine now.

**Comment by bglw** [comment]
Interesting — So 0.6.1 is working and 0.8.1 was not working?

**Comment by RenaudDev** [comment]
> Interesting — So 0.6.1 is working and 0.8.1 was not working?

Yes exactly

**Comment by bglw** [comment]
Thanks for the context — `0.7.0`/`0.7.1` is when the `pagefind_extended` binary was added and was made the default for the npx wrapper, so something in that changeover has obviously failed. I'll inspect that

**Comment by bglw** [comment]
Sorry for the delay all — this should be fixed by #113 — aiming for a release this week 🙂

**Comment by bglw** [comment]
👋 Hello! This is fixed in the [Pagefind v0.9.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.9.0) release 🎉

**Comment by bglw** [comment]
Sorry, false start — 0.9.1 going out which is on track to resolve this 🤞

**Comment by bglw** [comment]
👋 Hello! This is fixed in the [Pagefind v0.9.1](https://github.com/CloudCannon/pagefind/releases/tag/v0.9.0) release 🎉
