### ISSUE TITLE
Pagefind UI: debounce user input?

### ISSUE THREAD

**Issue by bglw** [CloudCannon/pagefind#105]
### Discussed in https://github.com/CloudCannon/pagefind/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **dprothero** October 21, 2022</sup>
Is there a way to have the UI debounce the user input? It's really distracting to have search results showing up for every key press.

In other words, don't have the search actually execute until something like 300ms after the last key press.</div>

**Comment by dprothero** [comment]
I'm taking a look at this right now.

**Comment by dprothero** [comment]
@bglw I opened PR #110. Let me know what you think.

**Comment by bglw** [comment]
Released in v0.9.0 🙌 🎉 Thanks again!
