### ISSUE TITLE
Unable to index compressed pages

### ISSUE THREAD

**Issue by chrisspen** [CloudCannon/pagefind#132]
How do you index compressed html files?

I have a large static site with around ~100k html files. My static site generator outputs gzipped compressed html files, which get uploaded to S3. The compression saves a ton of money a month on hosting costs, and every modern browser than auto-detect and depress gzipped html files, so it's a necessary publication format.

However, I'm walking through you [getting started docs](https://pagefind.app/docs/config-sources/) and `npx pagefind` is failing when it tries to walk my build directory:

    Running Pagefind v0.9.1 (Extended)
    Running from: "/var/project"
    Source:       "build"
    Bundle Directory:  "_pagefind"

    [Walking source directory]
    Found 90544 files matching **/*.{html}

    [Parsing files]
    Did not find a data-pagefind-body element on the site.
    ↳ Indexing all <body> elements on the site.
    90544 pages found without an <html> element. 
    Pages without an outer <html> element will not be processed by default. 
    If adding this element is not possible, use the root selector config to target a different root element.

    [Reading languages]
    Discovered 0 languages: 

    [Building search indexes]
    Total: 
      Indexed 0 languages
      Indexed 0 pages
      Indexed 0 words
      Indexed 0 filters
      Indexed 0 sorts
    Error: Pagefind wasn't able to build an index. 
    Most likely, the directory passed to Pagefind was empty or did not contain any html files.

So it looks like it's seeing my files but not finding any <html> tags, even though each page definitely contains an <html> tag. Why is this?

My build directory isn't flat and is structured like:

    build
        category1
             subcategory1
                 index.html
             subcategory2
                 index.html
             subcategory3
                 index.html
              ...
         ...

Is it failing to find any files because of my structure, or because of the gzip compression?

Either way, how would I resolve this?

For practicality reasons, I'm unable to change the folder structure nor remove gzip compression.

**Comment by bglw** [comment]
Hi @chrisspen 👋 

As of [Pagefind v0.9.2](https://github.com/CloudCannon/pagefind/releases/tag/v0.9.2), gzipped files will be handled automatically. Let me know how that goes — curious to hear what the indexing speed is like with this update.

**Comment by chrisspen** [comment]
Thanks, that's great. Is there any special requirement to activate the decompression?

I upgraded to 0.9.2 and disabled the decompression in my named pipes, so pagefind sees the raw gzip data, but it reports it now can't see any <html> tags:

    [Walking source directory]
    Found 679 files matching **/*.{html}

    [Parsing files]
    Did not find a data-pagefind-body element on the site.
    ↳ Indexing all <body> elements on the site.
    679 pages found without an <html> element. 
    Pages without an outer <html> element will not be processed by default. 
    If adding this element is not possible, use the root selector config to target a different root element.

If I test the file like `cat path/to/my/compressed/file.html | gunzip` it outputs valid html, containing an <html> tag.

Is Pagefind expecting the file to end with a .gz extension?

**Comment by bglw** [comment]
Hmm, no special handling needed, it should all be automatic. For reference, this is the test case:

https://github.com/CloudCannon/pagefind/blob/dfb07b09939b934664bed7a6986b03791fd35994/pagefind/features/input_quirks.feature#L11-L33

It seems to be working fine for me if I test it on my machine: https://app.warp.dev/block/2DI0I35XdrdS8ANfqBShn0

**Comment by bglw** [comment]
Could you paste in what the output of the following is?

```bash
head -c 3 path/to/my/compressed/file.html | hexdump
```

Perhaps Pagefind isn't recognizing the gzip header

**Comment by chrisspen** [comment]
0000000 8b1f 0008                              
    0000003

**Comment by bglw** [comment]
Hmm, that looks correct. [^1]

Unfortunately that means I might need to debug. Would you be willing to provide:

- An example compressed source file that isn't working
- The command/library you're using to compress files
- Information on the os + arch you're running Pagefind on?

[^1]: Well I was actually looking for `1f 8b 08` but I believe `8b1f 0008` is how it will appear with two-byte grouping (or on a big-endian system..?)

**Comment by chrisspen** [comment]
I'll check. It might be a bug on my end.

**Comment by bglw** [comment]
Hi @chrisspen — did you track this down on your end?

**Comment by chrisspen** [comment]
No, but I can't formula a MRE to send you either. I'd consider this issue resolved for now.
