### ISSUE TITLE
Not working on Safari (multi-OS)

### ISSUE THREAD

**Issue by brycewray** [CloudCannon/pagefind#178]
Pagefind on my site (https://www.brycewray.com/search) isn’t working on Safari on the latest versions — released a few days ago — of macOS, iOS, and iPadOS. It just hangs on the “Searching...” line. Moreover, using the Inspector shows none of the usual JS and “fragment” files loading, and I see no errors in the Console.

There are no such issues with Chrome, Microsoft Edge, or Firefox on macOS or Windows (the latter tested with Parallels Desktop on macOS); Pagefind still works normally there. Of course, all browsers on iOS and iPadOS are essentially Safari, so the no-load behavior is the same on any browser on those OSs. 

Have also reproduced in local dev-server testing as well on actual site in both [Hugo](https://github.com/brycewray/hugo_site) and [Eleventy](https://github.com/brycewray/eleventy_site) repos. This apparently precludes the possibility that it’s either host-related or GitHub-Actions-related.

**Comment by brycewray** [comment]
This is apparently host-related. Sorry to trouble you!

**Comment by bglw** [comment]
Oh no, I've jumped the gun on a [negative lookbehind](https://caniuse.com/js-regexp-lookbehind) 😭 I'll change that regex and release a new version, thanks for the find!

**Comment by brycewray** [comment]
@bglw Can conform Pagefind 0.10.6 has fixed this issue. Thanks as always!
