### ISSUE TITLE
Windows binary release

### ISSUE THREAD

**Issue by vanbroup** [CloudCannon/pagefind#18]
It would be great to have a Windows binary release for when updating Hugo pages on a Windows desktop.

**Comment by bglw** [comment]
Certainly! I'm hoping to get that up next week once I get time to update the deployment actions. 

If you're in a pinch, `cargo install pagefind` will work on Windows if you have cargo/Rust installed. I'll let you know when the `npx` path will work on Windows :) 

Cheers!

**Comment by bglw** [comment]
Hi @vanbroup — npx support & Windows binaries are now released as of `v0.6.1` 🎉 🙂
