### ISSUE TITLE
Unable to load PageFind UI - getting a 404

### ISSUE THREAD

**Issue by rrajath** [CloudCannon/pagefind#188]
Hi,
I tried adding PageFind to my hugo blog by following the [video on PageFind homepage](https://pagefind.app) as well as the [documentation](https://pagefind.app/docs). However, the search box isn't loading. The console shows the following error:

```
GEThttps://rrajath.com/_pagefind/pagefind-ui.js    [HTTP/2 404 Not Found 14ms]
GEThttps://rrajath.com/_pagefind/pagefind-ui.css    [HTTP/2 404 Not Found 13ms]
Loading failed for the <script> with source “https://rrajath.com/_pagefind/pagefind-ui.js”.
Uncaught ReferenceError: PagefindUI is not defined
    <anonymous> https://rrajath.com/:82
    EventListener.handleEvent* https://rrajath.com/:81
[rrajath.com:82:7](https://rrajath.com/)
    <anonymous> https://rrajath.com/:82
    (Async: EventListener.handleEvent)
    <anonymous> https://rrajath.com/:81
```

I use GitHub pages for hosing my blog and I have 2 repositories: [one for writing the markdown files](https://github.com/rrajath/blog) and the [other for hosting the generated html files](https://github.com/rrajath/rrajath.github.io). The `public/` folder in the second repo (rrajath.github.io) has the `_pagefind/` folder and all the index files.

I added the [PageFind UI snippet](https://pagefind.app/docs/ui) to [head.html in my blog](https://github.com/rrajath/blog/blob/master/themes/ezhil/layouts/partials/head.html#L24-L31). But for some reason Hugo is unable to fetch the js and css files. I tried loading the page - https://rrajath.com/_pagefind/pagefind-ui.js and it gives me a 404 in the console.

Can someone please help me identify what's going wrong? I'm not sure what I'm missing.

**Comment by rrajath** [comment]
That worked like a charm. Thank you. Could you please update the documentation with this? Or I can send a PR if you can tell me where would be the best place to put this info in the docs.

**Comment by bglw** [comment]
I'm about to add a few things to the docs so I'll drop something in and run it past you 🙂

**Comment by bglw** [comment]
@rrajath I've added a section **Hosting on GitHub Pages** here: https://unreleased.pagefind.app/docs/hosting/ — and renamed this page in the navigation to **Troubleshoot Hosting**

Do you think you would have discovered the answer with this in place?

**Comment by rrajath** [comment]
Looks good. Thank you for adding it. Couple of questions though:
1. I added a pagefind.yml file in my hugo project that has the configuration for bundle-dir set to `pagefind`. Not sure if that was needed. If so, maybe the documentation needs to also mention about adding pagefind.yml in the hugo project?
2. It looks like pagefind command must be run every time a new page is added in Hugo in order to update indexes. Can this be automated during hugo build? If so, can this also be added to the docs.

**Comment by bglw** [comment]
> I added a pagefind.yml file in my hugo project ... Not sure if that was needed

That's definitely one way to do it, or you can just pass the `--bundle-dir` flag to the Pagefind CLI. That flow is documented here: https://pagefind.app/docs/config-sources/

> Can this be automated during hugo build?

This setup can be done in a range of ways, which is why I haven't documented any one in specific. For GH pages you generally do have to run it each time, unless you set that up as a GitHub Action that can run and deploy the site.

Rather than document all service providers, I've added a new area to the docs for linking to posts others have written about their Pagefind setups. You can see this here: https://pagefind.app/docs/resources/

Browsing through those posts can shed some light on how others have configured things in their SSGs, or in their hosting environments. I'll keep an eye out for a good article targeting GH pages specifically 🙂

**Comment by rrajath** [comment]
Huh. I don't know how I missed the ˚Community Resources" section. Thanks again 🙂

**Comment by bglw** [comment]
Oh, to clarify, I only added that page to the docs today 😅

**Comment by rrajath** [comment]
Ah. Phew! I'm not crazy then. 😂
