### ISSUE TITLE
The version 0.10.6 doesn't work on Apple M1

### ISSUE THREAD

**Issue by oscarotero** [CloudCannon/pagefind#196]
Seems like the latest version fails with Apple M1 processors. Sorry, I cannot give more info because I don't have a Apple M1, but I have receive a couple of reports related to this.

Related issues: https://github.com/lumeland/lume/issues/362

The previous version 0.10.5 works fine.

**Comment by bglw** [comment]
Hmm, I've done a wee dive and I don't _think_ this is on Pagefind's end — perplexingly. Pagefind is working as expected on my M1 machine, but I can reproduce the Lume error.

I'll continue the conversation back in lumeland/lume#362
