### ISSUE TITLE
Minify JavaScript and CSS

### ISSUE THREAD

**Issue by vanbroup** [CloudCannon/pagefind#20]
While `pagefind.js` is minimized, the size of the other assets can be further reduced:

![image](https://user-images.githubusercontent.com/722070/179779784-cd396104-6cfb-45b2-a5c7-042551e613da.png)

**Comment by bglw** [comment]
Good call! This was an omission.

**Comment by bglw** [comment]
Hi @vanbroup 👋 

Pagefind UI asset compression has been fixed in [Pagefind v0.5.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.5.0) 🎉
