### ISSUE TITLE
Run without a webserver

### ISSUE THREAD

**Issue by karalabe** [CloudCannon/pagefind#202]
If I try to use pagefind currently loaded from a simple HTML file, it will fail with

```
pagefind-ui.js:1 Uncaught (in promise) TypeError: Failed to resolve module specifier '[...]/_pagefind/pagefind.js'. The base URL is about:blank because import() is called from a CORS-cross-origin script.
    at HTMLInputElement.ut (pagefind-ui.js:1:37346)
```

This seems like a strange thing to fail on, because I'd expect pagefind to just work with completely static files - since everything needed is already there. It does work if being served via any webserver.

Would it be possible to fix this, as it would allow completely static backups of a site to be searchable too without having to run `pagefind --serve`?

**Comment by bglw** [comment]
Hi @karalabe 👋 

Unfortunately Pagefind as it stands is fairly incompatible without being behind a webserver. It relies on JS modules, which I don't think have any support in the `file://` protocol, and similarly I don't _think_ webassembly works in this realm either 😕

Sorry to not have better news, but at this point using some static webserver is the only real solution (I usually use `python3 -m http.server` to spin something quick up on a machine without installs)

**Comment by karalabe** [comment]
That’s ok! Unfortunate and annoying, but I’m mostly clueless on the .js
department so I’ll take your word for it. Sweet project nonetheless!
