### ISSUE TITLE
Value Error : color Parse Error ----pagefind-ui-primary)

### ISSUE THREAD

**Issue by hashborgir** [CloudCannon/pagefind#207]
The W3C CSS Validation Service

```
CSS Validation error:
_pagefind/pagefind-ui.css
1		Value Error : color Parse Error ----pagefind-ui-primary)
```

It seems the binary ./pagefind inserts these files/bundle into the _pagefind directory in Hugo's 'public' directory. This happens each time I build my site/update it, so I'm not sure how to edit the source to fix this validation error. 

Please advise. Otherwise, there are no CSS errors.

There are plenty of warnings as well:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fwww.psychedelicsdaily.com%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by bglw** [comment]
Thanks! That error was a typo — fixed on `main` and will be in the next release. It looks like most of the warnings are from vendor prefixes and CSS variables, so I don't think there's anything useful to action there.
