### ISSUE TITLE
Publish pagefind-ui NPM package

### ISSUE THREAD

**Issue by shishkin** [CloudCannon/pagefind#209]
I wonder if you considered publishing UI as an NPM package (or part of the node wrapper package). It would be useful in a context of a more JS-heavy framework like Next.js or Astro as it would allow to import UI JS and CSS into a framework-specific component and leverage framework's asset pipeline. As a benefit, pagefind dependency could be localized to a single component instead of spread between the component and the layout. Also, it would enable pagefind UI in framework's dev mode when static output is not available (though it won't be "working" without the indexing being part of the framework's dev server too, which will need to be integrated separately as a plugin).

**Comment by bglw** [comment]
I would love to do something for this! I don't exactly know the best way I would package the existing UI to work in any given framework, since it's a compiled Svelte app. 

My current plan is to provide a set of UI components from Pagefind, and open up a section of the documentation for people to create and publish their own UI components — in this world I think it would make sense to have a separate "Pagefind React" component, or "Pagefind Svelte" component, et cetera.

A good first step could be publishing the existing UI as a Svelte package, since it should be a small lift there — I'll just need to look at some existing examples of Svelte components on npm.

I think we would then be better served by a separate React component — the UI codebase of Pagefind is really tiny (especially excluding the CSS) so I'm not too worried about maintaining multiple UI implementations.

**Comment by bglw** [comment]
NB: The main downside here is that the two would no longer be versioned synchronously — for development up until now it has been a great benefit to have this tight coupling for releases. I'll want to think through any future breaking changes and fast-track those before making this switch fully

**Comment by shishkin** [comment]
> I don't exactly know the best way I would package the existing UI to work in any given framework

I think packaging a minified ESM JS + .d.ts + CSS would be enough for any framework to be able to easily wrap it.

Another option would be to distribute the UI as a custom element web component. And Svelte [can produce those](https://svelte.dev/docs#run-time-custom-element-api).

You might also want to consider [Mitosis](https://github.com/BuilderIO/mitosis) (I haven't tried it myself) to cross-build the component for various target frameworks from a single source (JSX and Svelte are supported).

**Comment by bglw** [comment]
👋 @shishkin I'm in the process of doing a first pass over this (in preparation for adding a second Pagefind UI path)

I haven't put it on a stable release yet, but if you wanted to give it a spin you can install `@pagefind/default-ui` on `0.11.0-rc3` — keen to hear if that works out for you.

The following code snippet is working for me on my site:
```js
import { PagefindUI } from '@pagefind/default-ui'

window.addEventListener('DOMContentLoaded', (event) => {
    new PagefindUI({ element: "#search" });
});
```

Importing the CSS will depend on the framework — for my setup `import styles from "@pagefind/default-ui/css/ui.css";` is emitting that file fine 👍 

Let me know if you get a chance to take a look! This will be part of the next stable release 🙂

**Comment by shishkin** [comment]
Wow, thanks @bglw! That's awesome.

I was able to use it in Astro like this:

```astro
---
import "@pagefind/default-ui/npm_dist/ui.css";
---

<script>
  import { PagefindUI } from "@pagefind/default-ui/npm_dist/mjs/ui-core.js";
  window.addEventListener("DOMContentLoaded", () => {
    new PagefindUI({
      element: "#search",
    });
  });
</script>
<div id="search"></div>
```

I also had to define types for it:

```ts
// env.d.ts
declare module "@pagefind/default-ui/npm_dist/mjs/ui-core.js" {
  declare class PagefindUI {
    constructor(arg: any);
  }
}
```

When importing the ESM file directly I was getting this warning from Astro though it all worked fine:

```
pagefind doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.
```

So when the package is declared as `type: "module"` and has proper typings it all should work.

**Comment by hashborgir** [comment]
I don't use node. I despise java script so this won't be useful to me/for me. There should be a non dependency on anything clean way to load assets from Hugo without depending on node or anything else.

**Comment by bglw** [comment]
@hashborgir the normal flow won't change, so these files will always be available in the output directory of your site as they currently are. Publishing through npm is just an alternative distribution method for people using bundlers.

**Comment by bglw** [comment]
Hi @shishkin — this is now released on stable with [v0.11.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.11.0). I think I've addressed the warnings you hit by specifying specific `cjs` and `mjs` files — let me know if that is now the case. I forgot to wire up basic typing in this release sorry, but a future release will include them.

**Comment by shishkin** [comment]
Thanks @bglw , 0.11.0 works much better now.

I figured the `pagefind doesn't appear to be written in CJS...` warning comes from the `pagefind` main package as it seems to be rudimentary and the warning goes away if I remove it from my `package.json`. Maybe you could convert it to ESM or rename `.js` files to `.cjs`.

I've also written a small plugin for Astro that runs pagefind index during static build and serves the previously built `_pagefind` directory in dev server. That makes the DX quite good, though the index won't get hot-reloaded.

Look forward to the update with type definitions.

**Comment by shishkin** [comment]
I've just published my [Astro plugin](https://github.com/shishkin/astro-pagefind) as [NPM package](https://www.npmjs.com/package/astro-pagefind) in case anybody is interested.

@bglw maybe you could add it to https://pagefind.app/docs/resources/.
