### ISSUE TITLE
Pagefind UI: Possibility to preset search string

### ISSUE THREAD

**Issue by kristofzerbe** [CloudCannon/pagefind#214]
I've build a search page with Pagefind UI, which includes search parameters, but actually I can't preset the incoming search string, neither as init option nor via callback after init. Read about my workaround here: https://kiko.io/post/Pagefind-UI-and-URL-Parameters/

Would be great to have the option to preset a search string on init and automatic execution of the search if it's present.

**Comment by bglw** [comment]
Hi @kristofzerbe 👋 

I forgot that I still haven't documented this method for Pagefind UI, which is my bad. It does exist:

```js
let pagefind = new PagefindUI({ element: "#search" });
pagefind.triggerSearch("some search terms");
```

You also do not need to wait for any initialization to use this method, Pagefind will delay it until the search is loaded and ready.

You can see some discussion for this in #144 — I'll make sure to get this in the documentation soon (especially with a similar method #213 going out in the next release). Let me know if this works for you!

**Comment by kristofzerbe** [comment]
:D ... wonderful. Will try it out soon and update my post. Thanks for your incredible work.

**Comment by kristofzerbe** [comment]
Implemented, running, post updated... 👍🏼 

https://kiko.io/post/Pagefind-UI-and-URL-Parameters/

**Comment by kristofzerbe** [comment]
...

**Comment by kristofzerbe** [comment]
Hi Werner,

Pagefind UI has sort of a callback function called "`ProcessResult`", where you can do thing before the result is rendered (see https://pagefind.app/docs/ui/). At this point of time the search string is already processed. 

I would use it to take the search string out of the input field and add it to the URL via `history.pushState` ... see https://stackoverflow.com/questions/136458/change-the-url-in-the-browser-without-loading-the-new-page-using-javascript

Greets from Hessen
Kristof

**Comment by flyfoto** [comment]
Thanks for the tip, Kristof
that might work.
In additiona I am wondering how to add the currently selected filter state as parameters to the URL and vice-versa initialize the filter settings from the URL - ideally by extension of the default-UI.
Has anybody tried this already?
