### ISSUE TITLE
Hide empty filters

### ISSUE THREAD

**Issue by vanbroup** [CloudCannon/pagefind#23]
Currently the filter in the search results shows many values with no results `Value (0)`, it would make it more user friendly if those items would be hidden automatically:

![image](https://user-images.githubusercontent.com/722070/179932588-27ee7564-268c-4800-bc18-1778d1559ad5.png)

**Comment by bglw** [comment]
Good idea. It does depend on how many values there are — I personally like the explicit (0) when there are only three or four filters — but I see no reason this can't be added as an option.

**Comment by vanbroup** [comment]
When there are only a few it could make sense (it would tell you these are not available) maybe the check-box could be disabled in these cases. 

We have many tags (the ones on the screenshot are just the start) and a few dozen authors, so we would really appreciate the option to hide.
