### ISSUE TITLE
Multiples filters may obscure the result list on small screen mobiles where the lower half of the screen is overlayed by the soft-keyboard

### ISSUE THREAD

**Issue by flyfoto** [CloudCannon/pagefind#236]
![grafik](https://user-images.githubusercontent.com/125903677/221791700-0e7e954a-9f38-4f67-8ffc-f26e24c84fea.png)

I suggest to show the complete filter panel initially in collapsed state to improve the UX on mobiles.

As a workaround i decreased padding and UI-size to come to the ugly solution below:
![grafik](https://user-images.githubusercontent.com/125903677/221792363-5a795d39-da9b-43e8-a973-ecf47bb6eda3.png)

**Comment by bglw** [comment]
Yes, this is indeed an issue — I'll hopefully be looking at this area soon. For now, I'll merge this with #50

**Comment by flyfoto** [comment]
With the default of the component UI Filter rendering is now are much more convenient. It was worth waiting for the 1.5. Release. Thank you bglw!
