### ISSUE TITLE
Filter-counts are not reset after a seach field is cleared

### ISSUE THREAD

**Issue by flyfoto** [CloudCannon/pagefind#237]
After entering the search field (of the default UI) the filtes area initialized with their respective counts:
![grafik](https://user-images.githubusercontent.com/125903677/221793205-413e3024-1314-4e50-bd45-c86938625a29.png)
and then updated according to search term entered:
![grafik](https://user-images.githubusercontent.com/125903677/221793757-1fa8e1e8-e13b-4cc4-af63-e5d126617e4f.png)
However, after clearing the search field agan, the filtes still show the old counts:
![grafik](https://user-images.githubusercontent.com/125903677/221794035-b748a832-baac-4588-a322-1d83eea671d0.png)
I would expect the same counts as in the 1st step (or after refresh).

**Comment by bglw** [comment]
The fact that the filters remained open in this case was a bug introduced in v0.11.0 — the latest [v0.12.0 release](https://github.com/CloudCannon/pagefind/releases/tag/v0.12.0) fixes this and closes the filter panel when no search term is entered 🙂
