### ISSUE TITLE
Pagefind UI not shown on Hugo.

### ISSUE THREAD

**Issue by Huang-Zifeng** [CloudCannon/pagefind#240]
I publish my page on github page and use github action, I try hard but the ui doesn't appear.

When I run locally with npx pagefind --source "docs" --serve, I open the link and it redirects to the Internet site.

When I use github action with

```
- name: Run Pagefind
              run: npx -y pagefind --source docs --bundle-dir mysearch
```
the ui doesn't appear.

My hugo site respotitory is at https://github.com/Huang-Zifeng/Huang-Zifeng.github.io.

Any help will be appreciated!

**Comment by Huang-Zifeng** [comment]
I succeed in running it locally.

And although my [GHA dosen't report a bug](https://github.com/Huang-Zifeng/Huang-Zifeng.github.io/actions/runs/4335133486), but the UI is still missing.

**Comment by Huang-Zifeng** [comment]
I don't know where the problem is since my [workflow](https://github.com/Huang-Zifeng/Huang-Zifeng.github.io/actions/runs/4346415137) dosen't report any error.

**Comment by Huang-Zifeng** [comment]
I think maybe the problem lies in the pagefind don't really index. I see the page-find-ui.js and page-find-ui.css are both loaded.
![image](https://user-images.githubusercontent.com/110339237/223309191-151b5b8d-d986-4b1c-9d9f-527064929d7d.png)
But in the workflow I also found pagefind is running. 
![image](https://user-images.githubusercontent.com/110339237/223309333-70ac1aba-cc4a-4235-b6ae-bcf693d40a93.png)
Thanks for any advice!

**Comment by bglw** [comment]
Hey @Huang-Zifeng 👋 Sorry for the delay.

If [this](https://www.huang-zifeng.com/zh/2023/03/05/pagefind/) is the page I should be looking at, I think the issue might be that the `DOMContentLoaded` event is happening too quick, so the Pagefind code is not running. One option would be to replace the entire script contents with
```js
new PagefindUI({element:"#search"})
```
As long as the script is on the page below the `#search` element, there shouldn't be an issue. A more generic solution would be to follow the advice of [this post](https://stackoverflow.com/a/39993724) and check the document state, but it doesn't look like it would be needed in this instance.

Sorry that the documentation led you astray here! I'll look at improving it to avoid this edge case. Let me know if either of the above fixes resolve the issue for you 🙂
