### ISSUE TITLE
partial indexing

### ISSUE THREAD

**Issue by gedw99** [CloudCannon/pagefind#256]
Is there a way to tell it to only index a single folder ?

When i get up to 100,000 pages its slow and so instead i would like to tell pagefind to index a folder when i know that new html is in that folder.

**Comment by bglw** [comment]
👋 Hey @gedw99 

There isn't just yet, but I am hoping to get to that very soon. The existing issue for this is at #71 with the latest update here: https://github.com/CloudCannon/pagefind/issues/71#issuecomment-1401301921

Until that work is done, what I have seen people do is use [Pagefind's multi-site mode](https://pagefind.app/docs/multisite/) to index a site in a couple of sections, and then search both in the browser. It does come out to a little more bandwidth to load two indexes, but it can help cut down build speed.

I'll close this issue out but feel free to drop any comments on the main issue for this 🙂
