### ISSUE TITLE
Support files other than *.html

### ISSUE THREAD

**Issue by bcc** [CloudCannon/pagefind#26]
It would be helpful (for me at least) if pagefind were able to index files other than those named *.html.

For long and complicated (20+ year old) reasons the pages built by my static site generator have a '.shtml' extension and pagefind ignores them by default. I've hacked this up locally, but it would be great if you could optionally choose an extension or ideally glob pattern. 

Otherwise what a brilliant piece of software!

**Comment by bglw** [comment]
Ah, interesting! Yes I can certainly add a configuration for that — we're [already globbing for files](https://github.com/CloudCannon/pagefind/blob/main/pagefind/src/lib.rs#L31), so I'll wire that up to our configuration and allow it to be changed.

As long as it's still valid-enough HTML to get through [lol-html](https://github.com/cloudflare/lol-html) it should work fine. I'll get that out this week for you 🙂

**Comment by bglw** [comment]
Hi @bcc  👋 

Support for configuring the glob pattern has been released in [Pagefind v0.5.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.5.0) 🎉
