### ISSUE TITLE
[feature request] Search any content while returning it's title info，friendly to site generated by markdown 

### ISSUE THREAD

**Issue by augusttty** [CloudCannon/pagefind#265]
Nowadays, we document things with markdown and convert it into a static html. But the problem is ,due to the flat structure, we cannot locate the result's title information.Which is commonly useful to show the result more user friendly. For example, in pagefind official docs:
## Search for "filter inline":
![image](https://pixa.anomanm.com/temp/akwnako.png)
## Can we locate the title "Tagging a filter inline" based on the search result? See blow:
![image](https://pixa.anomanm.com/temp/w5r56q.png)
It will be nice if pagefind can search any content while returning it's title info.(Maybe based on some custom html tag attributes?).Or the current api has a capability to handle this?please help if it does.

**Comment by bglw** [comment]
👋 Hey @augusttty — this seems aligned with the work being done in #215. If using the API on the `0.13.0-alpha.0` you can access some raw information on the page anchors and their location in the content, but there isn't yet a nice wrapper around that, and it doesn't return the text of the anchor. All of that is planned for inclusion in a 1.0 release soon(ish), so it's on the way 🙂

I'll close this copy of the thread, but feel free to pick a conversation back up in #215
