### ISSUE TITLE
New Install - no search results show

### ISSUE THREAD

**Issue by tyeeman** [CloudCannon/pagefind#276]
After running pagefind, it indexes all my html files but I get this under the search bar after searching for cookery - 

```
Searching for cookery...
```
No results show up and "cookery" does exist on a few pages. Any tips? I read through the troubleshooting doc and tried this - 
```
The most widely-supported solution at the current moment is to ensure your Content Security Policy allows script-src 'unsafe-eval', which will work in all browsers.
```
but the search bar disappeared!

Update - I used the browser console to see what's happening - 

```
Failed to load Pagefind metadata:
TypeError: NetworkError when attempting to fetch resource. pagefind.js:1:14992
Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:1414/_pagefind/pagefind-entry.json?ts=1681616403808 (“default-src”). pagefind.js:1:14147
```
Update 2 - The docs don't say how "default-src" can be modified to prevent this. Please tell.

Update 3 - I added "http://localhost:1414" to "default-src" along with "script-src 'self' 'wasm-unsafe-eval'", and now it works. Shall I leave it this way permanently?

**Comment by bglw** [comment]
Hey @tyeeman — what was your existing `Content Security Policy` before updating it? I haven't seen the `pagefind-entry.json` specifically get blocked before

**Comment by tyeeman** [comment]
Well, I had ```default-src 'none'```. I changed it to ```default-src 'self'``` and now everything works fine. Why would someone use "none"?

**Comment by bglw** [comment]
It looks like `none` blocks _all_ `fetch` calls — so is the strictest version of the rule. Next time I'm in those docs I'll add a note about making sure `default-src` includes `self`.
