### ISSUE TITLE
Add config option to pagefindUI to define how many results are returned

### ISSUE THREAD

**Issue by davidsneighbour** [CloudCannon/pagefind#292]
It appears the PagefindUI returns 5 results per request. The docs don't offer any clue if it's possible to set that value somewhere in the configuration. It would be nice to set that to an integer (for instance, something dividable by 3 if we want to design the results page with "cards in three columns").

**Comment by bglw** [comment]
Good note! Something I've been meaning to fix, I'll wire that up as an option. 

_(Self note: I should also support a max for the results in the [modular ui](https://www.npmjs.com/package/@pagefind/modular-ui), though that is an infinite scroll so is slightly different)_

**Comment by alkaest2002** [comment]
Hi folks, may I ask whether such improvement is planned to be implemented any time soon?

**Comment by bglw** [comment]
Thanks for the prompt @alkaest2002! Implemented in #497 which will go out with the next release 🙂

**Comment by bglw** [comment]
Released in [v1.0.4](https://github.com/CloudCannon/pagefind/releases/tag/v1.0.4) 🎉
