### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by bglw** [CloudCannon/pagefind#3]
Pagefind is currently using the English stemmer — this should be made configurable and ideally auto-detected.

If an internationalized website in folders is detected, Pagefind should run itself once for each language directory, using that language as the configuration.

**Comment by slamethendry** [comment]
Even for website that does not have proper internationalisation folders, if the site has mixed characters (i.e. latin and non-latin characters), if I enter non-latin search term, e.g. japanese, pagefind returns everything.  I wonder if it is possible to process non-latin words the same way as latin words / characters.

Although this is not full internationalisation, this at least makes pagefind usable for non-english / non-latin search terms.

Thanks for the nice library.

**Comment by bglw** [comment]
Hi @slamethendry — [v0.7.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.7.0) features full multilingual support 🎉 

Let me know if you hit any further hiccups
