### ISSUE TITLE
How does one use the pagefind JavaScript API within Sveltekit?

### ISSUE THREAD

**Issue by hankertrix** [CloudCannon/pagefind#327]
I want to use pagefind to search through my mostly statically generated website, but I'm running into a lot of issues trying to get pagefind to work. I'm also building a custom search UI, which is why I need the JavaScript API. I'm using Sveltekit 1.20.4 and am using Vite as the build tool. My build directory is Sveltekit's default build directory, `.svelte-kit`. All of the pages in the site are pre-rendered as well, except for this search page.

The files below are inside the folder `src/routes/search`.

This is the search UI in a `+page.svelte` file:
```svelte
<script lang="ts">
  export let data;
  const results = data.results;
</script>

{#each results as result}
  <div>{result.url}</div>
  <div>{result.excerpt}</div>
{/each}
```

This is the `+page.ts` file to search for the search term with pagefind before rendering the page:
```typescript
import type { LoadEvent } from "@sveltejs/kit";

export const prerender = false;

export async function load({ url }: LoadEvent) {
  const searchQuery = url.searchParams.get("q")?.trim();
  if (!searchQuery || searchQuery.length < 1) return { results: [] };
  const pagefind = await import("/_pagefind/pagefind.js");
  const search = await pagefind.search(searchQuery);
  const results = await Promise.all(search.results.map(r => r.data()));
  return { results: results };
}
```

The `import` statement to import pagefind in the `+page.ts` file cannot find pagefind, which is to be expected as the site hasn't been built yet and pagefind runs after the site has been built, but this would cause the build to fail. Running pagefind before building the site doesn't work either since there are no pre-rendered pages for pagefind to index.

Also, even when the site has been indexed, Sveltekit is unable to find the file that is being imported in the `await import("/_pagefind/pagefind.js");` statement despite the file existing. Changing the file path to the path where pagefind is located, like `await import("../../../.svelte-kit/_pagefind/pagefind.js");`, also doesn't work as pagefind throws a reference error that `location is not defined`, which I assume to be the browser's `window.location`.

Please help, thank you.

**Comment by hankertrix** [comment]
I have figured it out. The issue with pagefind is that the build fails because the `pagefind.js` file cannot be found since it is generated after building the application. To get the application to build successfully, you will need to ignore TypeScript checking for the `pagefind.js` import, like this:

The code below is the code in the `+page.ts` file above.
```typescript
import type { LoadEvent } from "@sveltejs/kit";

export const prerender = false;

export async function load({ url }: LoadEvent) {
  const searchQuery = url.searchParams.get("q")?.trim();
  if (!searchQuery || searchQuery.length < 1) return { results: [] };

  // @ts-ignore
  const pagefind = await import("/_pagefind/pagefind.js");
  const search = await pagefind.search(searchQuery);
  const results = await Promise.all(search.results.map(r => r.data()));
  return { results: results };
}
```

Now the build process for the application will succeed, but using `svelte-check` to check the files for errors would give you extremely long and impossible-to-read errors due to the `pagefind.js` import being checked. Since the file is imported, you also cannot exclude the file in `tsconfig.json` as the file it is being imported into is checked, unless you choose to exclude the file containing the search page as well, which I would rather not do. Since I'm using TypeScript for my application and I'm not using any JavaScript files, I will disable checking of JavaScript files in the `tsconfig.json`, like this:

```json
{
	"extends": "./.svelte-kit/tsconfig.json",
	"compilerOptions": {
		"allowJs": true,
		"checkJs": false,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"sourceMap": true,
		"strict": true
	},
  "include": [
		"./.svelte-kit/ambient.d.ts",
		"./vite.config.ts",
		"./src/**/*.js",
		"./src/**/*.ts",
		"./src/**/*.svelte",
		"./src/**/*.js",
		"./src/**/*.ts",
		"./src/**/*.svelte",
		"./tests/**/*.js",
		"./tests/**/*.ts",
		"./tests/**/*.svelte"
	],
	"exclude": [
		"./node_modules/**",
		"./.svelte-kit/[!ambient.d.ts]**"
	]
}
```

Under `compilerOptions`, set `checkJs` to `false`, like this: `"checkJs": false`.

If you are using JavaScript files with JSDoc, I don't really know how to help you in that case.

After doing all these, you should be able to use pagefind without any issues in Sveltekit if you are using TypeScript in all of your files.

You should also move the location of the pagefind bundle to the `src/lib/` folder so you can easily import pagefind in all of you components and pages. To do this, you can change the `"postbuild"` script in your `package.json` file, which I assume you already have, to `pagefind --source .svelte-kit --bundle_dir ../src/lib/.pagefind`. Substitute the `.svelte-kit` directory to the output directory that you have configured and the `.pagefind` folder to whatever you want. Do note that the bundle directory is with respect to the source directory, so if your source directory is `.svelte-kit`, the pagefind files will end up being in `.svelte-kit/../src/lib/.pagefind`. Alternatively, you can use a `pagefind.yml`, `pagefind.yaml`, `pagefind.json` and `pagefind.toml` file to configure the source directory and the bundle directory, [amongst other things](https://pagefind.app/docs/config-sources/), like this:

This is a JSON example since I'm using TypeScript
```json
{
  "source": ".svelte-kit",
  "bundle_dir": "../src/lib/.pagefind"
}
```

Do add the directory containing the pagefind bundle to your `.gitignore` file as it will be recreated every single time you build the application, like this:

`.gitignore`
```gitignore
/src/lib/.pagefind
```

After doing all this, you will now be able to import the pagefind library using the `$lib` alias, like this:

```typescript
// @ts-ignore
const pagefind = await import("$lib/.pagefind/pagefind.js");
```

The `+page.ts` file from earlier edited to use the `$lib` alias.
```typescript
import type { LoadEvent } from "@sveltejs/kit";

export const prerender = false;

export async function load({ url }: LoadEvent) {
  const searchQuery = url.searchParams.get("q")?.trim();
  if (!searchQuery || searchQuery.length < 1) return { results: [] };

  // @ts-ignore
  const pagefind = await import("$lib/.pagefind/pagefind.js");
  const search = await pagefind.search(searchQuery);
  const results = await Promise.all(search.results.map(r => r.data()));
  return { results: results };
}
```

**Comment by bglw** [comment]
This is an awesome writeup, thanks for this @hankertrix 🙏 

One thing I'm hoping to do for the next large release is to publish an importable (typed) `pagefind` package to npm, that itself can hopefully wrap the dynamic import and make this a little more seamless. Keep an eye out for that 🙂

**Comment by hankertrix** [comment]
@bglw you're welcome! I also edited the post to add the solution to pagefind throwing a `ReferenceError: location is not defined` when being imported, which I missed out on when I made the post and also added the types I use for the pagefind library.

I'm definitely looking forward to a typed npm pagefind package, can't wait!

**Comment by hankertrix** [comment]
Here's a little update as I faced even more issues when trying to build and deploy to production using Pagefind with SvelteKit. I am using Vercel to deploy my application.

As it turns out, you can't move the Pagefind bundle outside of the build directory because the Pagefind bundle wouldn't be included in the built output of the site. As such, you shouldn't move the Pagefind directory to the `src/lib/` folder, which I recommended in my previous answer. The Pagefind bundle has to stay inside the build directory. I recommend just removing the bundle_dir property from the pagefind.json file (or leaving out the bundle_dir option when using the `pagefind` command) and leaving the bundle directory as default.

It also turns out that the `pagefind.js` file has hard-coded the import for the file called `pagefind-entry.json`, which is `/_pagefind/pagefind-entry.json`. This import is an import from a URL, so the actual path would be `https://your.website.here/_pagefind/pagefind-entry.json`. This means you are forced to use the `_pagefind` folder and cannot rename it or put it anywhere else, as changing the bundle_dir for the `pagefind` command doesn't seem to do anything to change this import. Without this import, the search library wouldn't work and your search page won't work. As such, you will have to point any imports of the Pagefind library to the `static` folder of your site, as SvelteKit uses the static folder to store any static assets, which are then made available after the site is built. So any files in the `static` folder, `static/*`, will be made available as `/*` on the website.

This also means that if you face issues with Vite failing to build your site on the hosting provider because of the Pagefind bundle not being found, you should build the site locally, let the `postbuild` script generate the Pagefind bundle, and then relocate the Pagefind bundle to the `static` folder. So your Pagefind bundle should be located in `./static/_pagefind` since I recommended that you leave the bundle directory as the default one. Make sure to add the Pagefind bundle to your git repository before pushing it to be deployed so that Vite will no longer complain about the `pagefind.js` file not being found. You should only need to do this once, as once Vite can find the file, it will no longer complain and the `postbuild` script to run the `pagefind` command should overwrite the `_pagefind` folder in the build directory generated by building the SvelteKit project. This means that the `pagefind.js` import in the search page will have to be changed to point to the `static` folder, like this:

```typescript
import type { LoadEvent } from "@sveltejs/kit";

/* This import has been added to check
if the environment the code is running in is the browser */
import { browser } from “$app/environment”;

export const prerender = false;

export async function load({ url }: LoadEvent) {
  const searchQuery = url.searchParams.get("q")?.trim();

  /* Add the check for the browser environment
  so that the function returns an empty list
  if the function is run on the server */
  if (!browser || !searchQuery || searchQuery.length < 1) return { results: [] };

  // @ts-ignore
  const pagefind = await import("$lib/../../static/_pagefind/pagefind.js");
  const search = await pagefind.search(searchQuery);
  const results = await Promise.all(search.results.map(r => r.data()));
  return { results: results };
}
```

I used the `$lib` alias as it is much easier to get to the root directory from the `src/lib/` folder than from the search page itself, especially if the search page is nested within multiple routes. I've found that using the `$lib` alias is also much less prone to errors compared to using a chain of `../`. You will still need the ts-ignore comment for the site to be built successfully, at least locally. I have no idea why the site fails to build on Vercel even with the ts-ignore comment.

I faced the above issue when trying to build and deploy to Vercel. For some reason, the site builds successfully when building the site locally, but when deploying to Vercel, Vite throws a load-fallback error saying that the `pagefind.js` file cannot be found. So I did the above steps and found that it works.

Hopefully this will help anyone trying to use Pagefind in their SvelteKit project.

**Comment by ZachSaucier** [comment]
This workaround, especially having to change things while working in development mode then changing it back before deploying, is not optimal.

Is there not a way to refer to the same data source for both working in development and for production? 

If not, is there a way to switch out the path(s) automatically based on whether or not it's running in development mode or in production?

**Comment by hankertrix** [comment]
It isn't optimal. The entire thing is a hack to get around the bundler (`vite`, `webpack`, etc) as they can't find the file and will throw an error during the build process. Especially `vite`, as it just ignores the `@ts-ignore` and `@ts-expect-error` comments and still causes the build to fail, which is why you'll have to get the `pagefind` index built beforehand with old or mock data before pushing the site the production to be built with the actual data.

I heard that handling this was going to be better with the release of a typed npm package that would deal with all of this, but I'm not sure if that is being worked on.

> Is there not a way to refer to the same data source for both working in development and for production? I would think that we could load the pagefind JS on the client side and use it to dynamically obtain the data needed for the searches if the index data was placed in the static directory.

You can definitely choose to load `pagefind` on the client side by setting the `ssr` option to `false`, as I documented above, but I chose not to do that.

> If not, is there a way to switch out the path(s) automatically based on whether or not it's running in development mode or in production?

You can use an environment variable to switch the paths out depending on whether you're in production or in development mode, either a `PAGEFIND_PATH` environment variable or code checking for the `ENVIRONMENT` environment variable to set the `pagefind` path.

**Comment by ZachSaucier** [comment]
I ended up using the `postbuild` step to also copy the resulting `pagefind` directory to the `static` directory. Here's the page I used:

```svelte
<script>
  import { onMount } from 'svelte';
  import { page } from '$app/stores';
  import { PagefindUI } from '@pagefind/default-ui';
  import '@pagefind/default-ui/css/ui.css';
  import { title_ending } from '$lib/config';

  onMount(() => {
    const pagefind = new PagefindUI({
      element: '#search',
      showSubResults: true,
      showImages: false,
      showEmptyFilters: false,
      autofocus: true,
    });
    pagefind.triggerSearch($page.url.searchParams.get('q'));
    const search_input = document.querySelector('#search input');
    search_input.addEventListener('input', (e) => {
      const search_params = new URLSearchParams(window.location.search);
      search_params.set('q', e.target.value);
      const new_url = `${window.location.pathname}?${search_params.toString()}`;
      history.pushState(null, '', new_url);
    });
  });
</script>

<svelte:head>
  <title>Search{title_ending}</title>
</svelte:head>

<div id="search" />
```

The `postbuild` command:

```
pagefind && rm -rf ./static/pagefind && cp -r ./build/pagefind/ ./static/pagefind/
```

**Comment by hankertrix** [comment]
I see you're using the UI bundled with `pagefind`. In that case, I don't think any of my solutions are needed to get `pagefind` to work properly. I think you simply need to import the `pagefind` UI component in your Svelte file and then use it like a normal Svelte component, and that should be all. You don't have to mess around with having the index built beforehand or whatsoever because `pagefind` deals with that for you, as you're importing the `pagefind` library directly instead of importing the web assembly binary that searches.

The reason why I wrote up all the things above is that I didn't want to use `pagefind`'s pre-built UI for searching and wanted to use the UI that I built, which is why I had to import the web assembly binary to get `pagefind`'s search. In your case, you shouldn't need to do any of this at all.

**Comment by ilkersigirci** [comment]
> I ended up using the `postbuild` step to also copy the resulting `pagefind` directory to the `static` directory. Here's the page I used:
> 
> ```svelte
> <script>
>   import { onMount } from 'svelte';
>   import { page } from '$app/stores';
>   import { PagefindUI } from '@pagefind/default-ui';
>   import '@pagefind/default-ui/css/ui.css';
>   import { title_ending } from '$lib/config';
> 
>   onMount(() => {
>     const pagefind = new PagefindUI({
>       element: '#search',
>       showSubResults: true,
>       showImages: false,
>       showEmptyFilters: false,
>       autofocus: true,
>     });
>     pagefind.triggerSearch($page.url.searchParams.get('q'));
>     const search_input = document.querySelector('#search input');
>     search_input.addEventListener('input', (e) => {
>       const search_params = new URLSearchParams(window.location.search);
>       search_params.set('q', e.target.value);
>       const new_url = `${window.location.pathname}?${search_params.toString()}`;
>       history.pushState(null, '', new_url);
>     });
>   });
> </script>
> 
> <svelte:head>
>   <title>Search{title_ending}</title>
> </svelte:head>
> 
> <div id="search" />
> ```
> 
> The `postbuild` command:
> 
> ```
> pagefind && rm -rf ./static/pagefind && cp -r ./build/pagefind/ ./static/pagefind/
> ```

Thx for this, this is what I was looking for when I figuring out how to use it to my SSG Sveltekit project. Unfortunately, this doesn't work if I done `npm run build && npm run preview`. It throws error `SvelteKitError: Not found: /pagefind/pagefind.js`.

I am using, pagefind 1.0.4 with sveltekit 2.0.0

**Comment by hankertrix** [comment]
> I think an official documentation is needed for integrating pagefind to framework like Sveltekit.

We definitely do need that. Not just for Sveltekit, but also for other frameworks like Next.js, Nuxt, SolidStart and Angular. The problem is ultimately the same for all of them, the pagefind library not existing before the build.

**Comment by hankertrix** [comment]
> It throws error SvelteKitError: Not found: /pagefind/pagefind.js.

@ilkersigirci for this issue, you most likely need to check your pagefind bundle directory. It seems to me that your site has been successfully built, considering that you are getting a SvelteKitError and not a Vite error. Check in the `build` folder (or whatever folder you have selected to be the build folder) for the pagefind folder and verify that the path is the same as the one that you have defined in your code, or is in the `static` folder if you are using the pagefind UI.

**Comment by hyunbinseo** [comment]
Why not use the plain `<svelte:head>` element instead?

This is how I got it to work: https://github.com/hyunbinseo/svelte-kit-pagefind/commit/a99285b7d1d4c6d68a511f9f2767bb00f1429758

You can try the demo at https://svelte-kit-pagefind.pages.dev/

**Comment by vnphanquang** [comment]
Sorry for digging this up, but this is what I settled with:

```ts
import(/* @vite-ignore */ `${origin}/pagefind/pagefind.js`).then((pagefind) => {
  pagefind.init();
  pagefind.search({ /* ... */ });
});
```

Note the `vite-ignore` directive and the `origin` prefix. Both are necessary in my test. Hope this is helpful.
