### ISSUE TITLE
allow directly passing in `HTMLElement` to default ui `element` option

### ISSUE THREAD

**Issue by stefanprobst** [CloudCannon/pagefind#330]
currently, the default pagefind ui expects a query selector string as `options.element`, see https://github.com/CloudCannon/pagefind/blob/main/pagefind_ui/default/ui-core.js#L40

it would be nice if it were possible to directly pass in a reference to an html element as well, i.e.:

```diff
- const dom = document.querySelector(selector);
+ const dom = selector instanceof HTMLElement ? selector : document.querySelector(selector);
```

would you accept a pr for this?

**Comment by bglw** [comment]
I would certainly accept a PR for this 🙂
