### ISSUE TITLE
pagefind does not execute on fresh windows system

### ISSUE THREAD

**Issue by Heinrichsgeist** [CloudCannon/pagefind#338]
I extracted and started "pagefind-v0.12.0-x86_64-pc-windows-msvc.tar.gz" on a fresh windows installation and got error message that vcruntime140.dll is missing. Easy to solve.

More frustrating is when you try "npx pagefind --source public --serve" on powershell and get no feedback why pagefind does not like to execute.

**Comment by bglw** [comment]
Hey @Heinrichsgeist — thanks for letting me know.

I'll update the build to statically link vcruntime (and anything else) on Windows, since ideally Pagefind has no installation requirements. I'll get this out on an alpha release before a stable one so it can be tested.

**Comment by bglw** [comment]
👋 The latest alpha release includes this static bundle, so this should be fixed. I'll close this issues once 1.0 is released.

**Comment by bglw** [comment]
Hey @Heinrichsgeist  ! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙
