### ISSUE TITLE
Next.js Support

### ISSUE THREAD

**Issue by j-mendez** [CloudCannon/pagefind#341]
Hi thank you for the amazing project!

There are a couple blockers for this to work with [next.js](https://nextjs.org/). 

## Blockers

1. Html output can only be handled when the project deploys with `output: static`.
2. The output when using static exports do not get mapped to the correct paths.

## Resolution

For the issues above the following project was created to help the missing gaps [auto-pagefind](https://github.com/a11ywatch/auto-pagefind).

The `auto-pagefind` project uses [spider](https://github.com/spider-rs/spider) to quickly download all the html locally (can also handle thousands of pages within milliseconds ). Afterwards the `pagefind` command is ran against the temp folder and content is moved to the `public` directory to utilize.

Posting this issue here to bring guidance towards next.js.

**Comment by bglw** [comment]
Very nice!

@j-mendez the latest alpha (and upcoming v1.0) has a feature that might help you develop this further.

If you check the README of the npm package ([wrappers/node/README.md](https://github.com/CloudCannon/pagefind/blob/main/wrappers/node/README.md)) you'll spy the new NodeJS indexing API. With this you can use the `pagefind` package and add content to a search index directly, without having to run the `pagefind` binary.

Let me know if that's of interest! It should be on a stable release within a month or so 🙂

**Comment by j-mendez** [comment]
@bglw thanks, I like it and think that can would help get the job done across the board - good stuff!

**Comment by bglw** [comment]
Hey @j-mendez  ! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

And see the new Node API docs here: https://pagefind.app/docs/node-api/
