### ISSUE TITLE
npx pagefind on win10 is error

### ISSUE THREAD

**Issue by gaohc001** [CloudCannon/pagefind#346]
vitepress use pnpm.
D:\WWW\myself\myBlog> npx pagefind --source docs\.vitepress\dist
Binary failed to download — package expected to have downloaded the binary to D:\WWW\myself\myBlog\node_modules\.pnpm\pagefind@0.12.0\node_modu
les\pagefind\bin\pagefind_extended.exe during its postinstall
Do you have install scripts disabled for npm?
Try running `npm config set ignore-scripts false` and re-installing.
Otherwise, your platform might not be supported. Open an issue on GitHub!

**Comment by bglw** [comment]
Hey @gaohc001 👋 

For pnpm you can use one of the following:

If you have `pagefind` added as a dependency of your project already:
```
pnpm exec pagefind
```

If you do not have `pagefind` added as a dependency:
```
pnpm dlx pagefind
```

Additionally, if you continue to hit a problem try upgrade Pagefind to the latest alpha version (`1.0.0-alpha.5`) as this removes the need for a postinstall script and is thus more reliable.

**Comment by bglw** [comment]
Assume this is covered so closing this issue out — drop a line if not!
