### ISSUE TITLE
CSP and “Load more results” button 

### ISSUE THREAD

**Issue by brycewray** [CloudCannon/pagefind#36]
As the docs counsel, I set my Content Security Policy’s `script-src` to `unsafe-eval`; however, that turned out to be insufficient. (I have put the CSP in `Report-Only` mode for now.) I also had to use `unsafe-inline`. That worked fine for the initial five loads but, when I used the **Load more results** button, I got this back:

```
[Report Only] Refused to send form data to 'javascript:void(0);' because it violates the following Content Security Policy directive: "form-action 'self' https://duckduckgo.com https://*.duckduckgo.com https://startpage.com https://*.startpage.com".
```

Short of just not having a `form-action` entry in the CSP, am not sure how to proceed on that one. My searches don’t seem to give a good answer.

This may be somewhat similar to [Issue #21](https://github.com/CloudCannon/pagefind/issues/21), but am just noting it FYI.

- Site: https://www.brycewray.com
- Repo: https://github.com/brycewray/hugo_site

P.S. All this aside, **very** nice job on the fixes between 0.4.1 and 0.5.0! 👍 👍 👍

**Comment by bglw** [comment]
Hi @brycewray! 👋 

Ah my bad on that form submission. That should be fixed now in [v0.5.1](https://github.com/CloudCannon/pagefind/releases/tag/v0.5.1).

I've added a note about `unsafe-inline` to the docs — this is only needed if you're using the inline `<script>` block to initialize Pagefind UI, you could avoid needing to set this by moving that Pagefind initialization into an allowed javascript file. 

Thanks for the kind words! Let me know if this fixes things for you 🙂
