### ISSUE TITLE
Some translated strings still appear in english

### ISSUE THREAD

**Issue by RoneoOrg** [CloudCannon/pagefind#374]
Hi there,

as you can see in the screenshot below, the UI is displayed in French, but the "Clear" button is however in english:

![pagefind-transliations](https://github.com/CloudCannon/pagefind/assets/77257518/f897ad4c-9208-4d83-ad31-00dcc19e82ef)

I checked in the repo and [the french translation is complete](https://github.com/CloudCannon/pagefind/blob/main/pagefind_ui/translations/fr.json), but some translations are not applied

**Comment by RoneoOrg** [comment]
Note that a second translation is not applied:

when the search form is empty, the english string "Search" is displayed, while the french string "Rechercher" should appear instead:

![pagefind-2](https://github.com/CloudCannon/pagefind/assets/77257518/05e9d2af-9f2a-4fe2-aee9-3a3bedfd0b6d)

**Comment by bglw** [comment]
Hey @RoneoOrg thanks for the report — this will be fixed in the 1.0 release next week.

**Comment by bglw** [comment]
Hey @itsmatteomanf 👋 

Looks like Italian translation strings were contributed after the current stable `0.12.0` release. They'll be available right now on the `beta` release tag, and will be in the 1.0 release 🙂

**Comment by bglw** [comment]
<img width="480" alt="Screenshot 2023-09-08 at 8 17 20 AM" src="https://github.com/CloudCannon/pagefind/assets/40188355/c97ec46e-27dc-434b-ae29-d2c716908824">

**Comment by itsmatteomanf** [comment]
I am using the 1.0.0 alpha releases, but I can check again...

**Comment by bglw** [comment]
NB: The fix for this issue where half of the strings sometimes appear untranslated is on the latest _beta_, not alpha. `v1.0.0-beta.2` currently.

**Comment by itsmatteomanf** [comment]
I might have been running into the same issue as OP here, I had *some* translations, but not all.

**Comment by bglw** [comment]
Hey all! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙
