### ISSUE TITLE
pagefind can't be installed using git bash

### ISSUE THREAD

**Issue by murtuzaalisurti** [CloudCannon/pagefind#376]
facing issues with installing pagefind using git-bash but gets installed perfectly using powershell on windows!

![bashPagefind](https://github.com/CloudCannon/pagefind/assets/68743212/72764b9c-dde1-4909-b609-2fd96592e778)

**Comment by bglw** [comment]
Hi @murtuzaalisurti 👋 

This should be fixed in the upcoming 1.0.0 release, where we changed distribution method slightly — if you run `npm i pagefind@alpha` it should install correctly 🙂

**Comment by murtuzaalisurti** [comment]
@bglw great, thanks!

**Comment by ATQQ** [comment]
Mark!

**Comment by bglw** [comment]
Hey all! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

**Comment by murtuzaalisurti** [comment]
it's fixed, thanks
