### ISSUE TITLE
Hyphenated phrases

### ISSUE THREAD

**Issue by brycewray** [CloudCannon/pagefind#39]
I tried searching for hyphenated words and phrases both with and without surrounding quotes — *e.g.*, `Go-based` and `"Go-based"` — but this doesn’t work with 0.5.3. The result shows up with zero hits. I don't know whether the ignoring of hyphens is on purpose but, if not, just FYI.

**Comment by bglw** [comment]
Ah yes, an artifact of my quick bugfix yesterday. I'm going to look at moving some more of this character-handling logic into the webassembly side of the equation so that it's always the same Rust code transforming terms. Aiming for next release 👍

**Comment by bglw** [comment]
Didn't make it into the multilingual release, but will be visited soon 🙂

**Comment by bglw** [comment]
Fixed!

**Comment by brycewray** [comment]
> Fixed!

Yes, just noticed that a little while ago with the 0.8.0 release. TY sir!
