### ISSUE TITLE
Situations where HTML isn’t well-formed

### ISSUE THREAD

**Issue by brycewray** [CloudCannon/pagefind#40]
This is more of an FYI than a true issue report.

In testing Pagefind with the Astro SSG, I’ve seen that it can’t index pages with malformed HTML even though browsers can manage to display the HTML normally. For example, Astro sometimes generates pages lacking the wrapping `<html></html>` (and Pagefind fails to index them, in my testing) even though the HTML does manage to have `<body></body>`. (Their team is aware of the issue, and I’ve seen similar such problems with Astro-generated HTML over the last few months. They seem to come and go.)

I’ve had no such problem with Hugo, where the HTML is always correct.

Haven’t tried Pagefind with Eleventy yet but, in two-and-a-half years of off-and-on use of Eleventy, I never saw it produce malformed HTML, so am guessing Pagefind would be fine with it, too.

**Comment by bglw** [comment]
Good FYI. Pagefind should be generally alright with malformed HTML (within the bounds of Cloudflare's [lol-html](https://github.com/cloudflare/lol-html) parser). The missing `html` element is a current frailty, though, as this is the default selector Pagefind bases all indexing on.

I believe if you configure the Pagefind [root selector option](https://pagefind.app/docs/config-options/#root-selector) on your Astro site to be, say, `body`, you'll see your pages index correctly. (Though you won't be able to get meta/filters from your `<head>`)

I can look at adding some warning logs if Pagefind encounters pages without an `html` element as a stop-gap.
