### ISSUE TITLE
Emojis not indexed? They return no results

### ISSUE THREAD

**Issue by Julianoe** [CloudCannon/pagefind#405]
Using PageFind with tweetback I've noticed that searching for emojis return no results ([issue here](https://github.com/tweetback/tweetback/issues/90))
Testing it on [your demo page](https://xkcd.pagefind.app/) confirmed that it did not work: searching for 🌋 should return this page as a result: https://xkcd.pagefind.app/comics/2017-11-24-emoji-sports/

Is it known behavior? Would there be a way to index emojis to enable searching for them like any other caracters?

**Comment by bglw** [comment]
Hey @Julianoe 👋 

The latest Pagefind beta (`1.0.0-beta.1`) includes support for emoji. There are also a couple of changes on the beta, most notably a rename from the default `/_pagefind/` to `/pagefind/`, which I haven't finalized a set of release notes for.

Let me know if you give this a go! It will be part of a full 1.0 release next week or so, so no worries if you just want to wait til then 🙂

In lieu of running it, here's the new test that now passes: https://raw.githubusercontent.com/CloudCannon/pagefind/main/pagefind/features/characters.feature
_(Search `Pagefind matches emoji`)_

**Comment by bglw** [comment]
Hey @Julianoe  ! 👋

Good news — this has landed in Pagefind v1.0.0! ✨

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

**Comment by Julianoe** [comment]
Awesome! Thanks!
