### ISSUE TITLE
Please update microjson

### ISSUE THREAD

**Issue by pbsds** [CloudCannon/pagefind#421]
Hi, I'm [packaging pagefind into nixpkgs](https://github.com/NixOS/nixpkgs/pull/247773), and we [struggle with git dependencies in cargo](https://github.com/NixOS/nixpkgs/pull/217084).

You seem to include a git reference to `microjson`:

https://github.com/CloudCannon/pagefind/blob/57507610870a1dcf94f10ce79604e43542a68df0/Cargo.lock#L1676-L1679

Could you update this to a non `git+...` dependency? Much appreciated.

**Comment by bglw** [comment]
Hi @pbsds — good to know!

I have another change to include in a 1.0.1, so I can include this. I'm blocked by a bug on the crates release of `microjson`, but I can do a temporary fork and publish a crate at that commit to unblock you. Will be in touch later today

**Comment by pbsds** [comment]
There is a 50/50 chance a reviewer will find it problematic or not that i vendor the lock as a fix so it is not a _total_ block, but please do keep me posted.

Congrats on 1.0.0 :rocket:

**Comment by bglw** [comment]
Just publishing a `1.0.1-rc1` release now to test both fixes — should have something out today assuming nothing else comes up 👍
