### ISSUE TITLE
Why Search results includes `_ END_PAGEFIND_WEIGHT`

### ISSUE THREAD

**Issue by ATQQ** [CloudCannon/pagefind#430]
Why Search results include `__END_PAGEFIND_WEIGHT` and `___ PAGEFIND_ANCHOR___h1`

![image](https://github.com/CloudCannon/pagefind/assets/42485491/9ddb40f2-8fb7-42ba-8eca-155d3e45e73f)

**Comment by bglw** [comment]
Hey @ATQQ 👋 — This is definitely a bug on my end, sorry about that! Pagefind uses those labels internally while parsing, but they aren't supposed to escape the machinery!

I'll work on a fix for this.

**Comment by ATQQ** [comment]
Looking forward to your fix, as pagefind upgraded v1 this week, I found this problem in the process of upgrading my plugin [vitepress-plugin-pagefind](https://www.npmjs.com/package/vitepress-plugin-pagefind)

---
As an aside, the features I discovered on pagefind alpha a long time ago don't seem to exist on 1.x latest?

**Comment by bglw** [comment]
I'll work on a fix today :) 

> As an aside, the features I discovered on pagefind alpha a long time ago don't seem to exist on 1.x latest?

What features specifically? I don't think anything was removed between an alpha release and 1.x

**Comment by ATQQ** [comment]
Below is the alpha version of the search results, it looks a little different from the latest results, such as anchors

![image](https://github.com/CloudCannon/pagefind/assets/42485491/4196f024-c655-4d16-9349-14a4843646e4)

Looks like it's the latest bug？

**Comment by bglw** [comment]
Ah — yes, the internal tokens leaking out is also causing them to _not_ be picked up as anchors, so they're missing there. Upcoming change will fix both 🙂

**Comment by ATQQ** [comment]
Then look forward to your repair, Thanks♪(· ω ·)ノ❤️

**Comment by bglw** [comment]
Hi @ATQQ 👋 

Pagefind `v1.0.3-rc0` hopefully fixes this, but I'll wait for a confirmation on this before publishing it fully. Would you be able to give that prerelease a quick test? 🙏

**Comment by ATQQ** [comment]
ok ，Give me some time. I'm currently outdoors

**Comment by bglw** [comment]
No rush! It's evening over here, so it might sit until morning 🙂

**Comment by ATQQ** [comment]
It should look normal, very perfect 😃 

![image](https://github.com/CloudCannon/pagefind/assets/42485491/adf5e99f-125b-4dff-909b-5b0f27bb0c81)

But there seems to be a new problem，Search results with some extra Spaces
* `0.x` Result: *解除注释后，就能看到模板首页<mark>背景图</mark>发生了变化*
* `1.x` Result:  *) ; } 解除 注释 后 ， 就 能 看到 模板 首页 <mark>背景图 </mark>...*

**Comment by bglw** [comment]
Ah, interesting. I was aware of that as an issue, but I did think it was **also** an issue in the `0.x` releases.

I'll have a look and see why that got introduced, and if there is an easy fix. 

( Thanks for the quick test ❤️ )

**Comment by bglw** [comment]
Hey @ATQQ — `v1.0.3-rc1` is out and I _think_ it's good to go!

I'll look at releasing it in ~12 hours. Let me know if you get a chance to try it beforehand, all good if not ☺️

**Comment by ATQQ** [comment]
I tested it and it was fine this time, very nice.

You're so efficient 👍 💯  @bglw

**Comment by bglw** [comment]
Released in `v1.0.3` 🙂
