### ISSUE TITLE
Delete current search term from search field

### ISSUE THREAD

**Issue by kimonostereo** [CloudCannon/pagefind#44]
Feature request: Would it be possible to have an option to easily delete the current search term from the search field? Maybe a "x" on the far right that deletes the current search term if clicked?

**Comment by bglw** [comment]
Yes, this can certainly be added 🙂

**Comment by jmichelgarcia** [comment]
I was looking into Pagefind after being disappointed by Algolia and I'm impressed so far. It's also much faster than lunr.js when it comes to displaying results 🥇.

Btw, I would also love for a way to dismiss the current search.

**Comment by whyboris** [comment]
Related: I find pressing the `esc` key to be a very intuitive way to clear input; I created an _Issue_ for it #124

**Comment by bglw** [comment]
Hi all — this is implemented now in [v0.11.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.11.0) :)
