### ISSUE TITLE
Issue on Yarn, Git Bash or Pagefind?

### ISSUE THREAD

**Issue by lovkyndig** [CloudCannon/pagefind#452]
The _node_modules/pagefind/bin/pagefind_extended.exe_-file is missing in my local development every time this file or package is cached on my windows mashine from earlier installations.

 `Git Bash` give and error about missing file before it finish the installation with an error. 

It's happend on `yarn install` and only the _pagefind_extended_-file is missing, not anything from other packages.

As said above, It's happend when some of the files is cached  after an installation in c:/users/myname/Appdata/Local/Temp/-folder from an earlier installation.

It have happend around 100 times (plus minus 50). Therefore I always have an backup of this file, and manually copying it to the bin-folder after the installation. (This takes less time then manually deleting all of the cached files in temp-folder before I start a new installation.) Then everything works fine.

My repo is here: https://github.com/lovkyndig/kirkepostille

I'm not sure if it's happend only when I'm using _Git Bash_ or if it's also happend in _Windows Cmd_.

**Updating importent info:**
Well, I have discovered that this is not at problem when I'm using Windows Cmd. The problem seems to be when using `Git Bash`. Maybe Yarn isn't the problem?

**Comment by bglw** [comment]
Hey @lovkyndig 👋 

I don't have a Windows machine handy to test this immediately — but first, could you run the following command in your Git Bash session and let me know what it logs?

```bash
node -e "console.log(process.platform)"
```

**Comment by bglw** [comment]
Hi @lovkyndig — did you manage to solve this issue? I’ve been moving and haven’t had my windows machine in action this week, but still keen to dig into it if you continue to have the issue

**Comment by lovkyndig** [comment]
Thanks for asking! I haven't got anymore errors. It can be that there was an issue with the git-repo I was working on earlier. The yarn.lock-file disappeared from the repo and never got back. But I see that pagefind also has uppgraded. 
I am very grateful for this free pagefind-package from CloudCannon. The search-functionality are alfa and omega for the sites I am working on.
God luch and thanks for the good work with pagefind!
