### ISSUE TITLE
Proper navigation to urls that are external

### ISSUE THREAD

**Issue by Enigmatrix** [CloudCannon/pagefind#468]
I'm working on search with links to sites that are not my own HTML content (specifically, they are links to external sites) and I can index them using the Pagefind NodeJS API as such:
```js
extUrl = "https://example.com/exams"
await index.addHTMLFile({
  url: extUrl,
  content: await fetch(extUrl).then((res) => res.text()),
});
```

However, while using default-ui search to find known keywords of this URL and navigating to the site, the target URL gets clobbered as `https://mysite/https:/example.com/exams`. This doesn't seem to be an issue on the pagefind Rust binary side, but the default-ui side (verified using my debugger). It uses `fullUri` to get the URL:

https://github.com/CloudCannon/pagefind/blob/9740deb41d1ba997b21bc65449c79dcced974427/pagefind_web_js/lib/coupled_search.ts#L248-L279

and this clobbers it. An easy fix would be to detect if the URL already starts with https / http and just leave it alone.

**Comment by bglw** [comment]
Ah, good call. Will fix.

**Comment by bglw** [comment]
Pending the next release, I think you would be able to use the [Default UI's processResult hook](https://unreleased.pagefind.app/docs/ui/#process-result) to unclobber it, if that helps!

**Comment by Enigmatrix** [comment]
ok thanks for the workaround 👍 , will await the fix as well.
