### ISSUE TITLE
Docs: wrong attribute in multiple-filter example?

### ISSUE THREAD

**Issue by olets** [CloudCannon/pagefind#473]
According to https://pagefind.app/docs/filtering/#specifying-multiple-filters-on-a-single-element, when providing multiple comma-separated filters the attribute `data-pagefind-metadata` should be used.

In my testing, that populates metadata. `data-pagefind-filter` seems to be the correct attribute, same as when single filter values.

**Comment by bglw** [comment]
Good spot! Lazy copy pasting on my part 🫣

Fixed!
