### ISSUE TITLE
Default UI not converting named Unicode characters like "&amp;" in headline of result

### ISSUE THREAD

**Issue by flyfoto** [CloudCannon/pagefind#476]
Thank you for eventually providing the improved V1.0 release! It was easy to upgrade and is fun to use.
Here is a small quirk I detected:
Since V1.0 a unicode character in &<CharacterID>; Syntax is no longer converted/renderd  in the headline of the result. This happens however correctly in the excerpt text below.
![IMG_0690](https://github.com/CloudCannon/pagefind/assets/125903677/fe90e2b8-974e-4618-a4cc-e2b511735fb2)
In pre 1.0 version it was displayed correctly :
![IMG_0689](https://github.com/CloudCannon/pagefind/assets/125903677/f9490821-d7f5-4570-82e4-e47a01fe8000)
Cheers
Werner

**Comment by bglw** [comment]
Fix released in [v1.0.4](https://github.com/CloudCannon/pagefind/releases/tag/v1.0.4) 🎉
