### ISSUE TITLE
Search API using Next.js: Failed to load Pagefind metadata

### ISSUE THREAD

**Issue by pmillspaugh** [CloudCannon/pagefind#482]
Hi, I am excited about Pagefind — thanks for creating it!

_Note: I originally asked this on Discussions (https://github.com/CloudCannon/pagefind/discussions/481). If it's not an appropriate issue (because it's a me issue not a pagefind issue), I'd be glad to take this down!_
## The error

I am running into a `Failed to load Pagefind metadata` error when initializing the Pagefind Search API in [this PR](https://github.com/pmillspaugh/petemillspaugh.com/pull/15/files). 

Pagefind throws the error in [this fetch call](https://github.com/CloudCannon/pagefind/blob/ca82a78e752f8199ebaff6c9aace5fcf812766c0/pagefind_web_js/lib/coupled_search.ts#L146). The browser adds info: `Not allowed to load local resource: file:///my/path/to/pagefind/pagefind-entry.json?ts=1697986568739`. How can I ensure that fetch points to my client-side bundle rather than trying to fetch a local file path?

## More info

I see that the Search API exposes `bundlePath` and `baseUrl` options, but I haven't had success altering those. I also tried explicitly calling `pagefind.init()` before `.search()`, which leads to the same error.

I also saw that a similar strategy [works in Astro](https://blog.otterlord.dev/posts/astro-search/), so I'm hoping there's just a small piece I'm missing.

**Comment by pmillspaugh** [comment]
I also tried outputting the search bundle into my static assets folder via `pagefind --output-path public/pagefind`, but that yields the same error. 

My guess is that the Next bundler resolves dynamic imports differently than in the Astro example with a vanilla script tag, so I tried swapping out the dynamic import for a static import. That breaks the build, throwing `ReferenceError: location is not defined` when attempting to load the script.

**Comment by pmillspaugh** [comment]
I realized my approach was a bit different than the one in the docs (and Astro example). I thought I should (1) build my static site bundle, (2) generate my pagefind search bundle and output it to my static asset dir `public/`, _then (2) re-build my static site bundle with the pagefind resources_.

So if I remove that third step, I (hopefully) just need to know where to output the pagefind search bundle in the second step, although that isn't immediately obvious to me. For example, it looks like my development mock file `/public/pagefind/pagefind.js` gets output into `.next/static/chunks/800.e63360a6622816d4.js` according to `react-loadable-manifest.json`:

```
{
  "search.tsx -> ../../public/pagefind/pagefind.js": {
    "id": 7800,
    "files": [
      "static/chunks/800.e63360a6622816d4.js"
    ]
  }
}
```

**Comment by bglw** [comment]
Hmm, I don't have experience piping Pagefind's scripts through a bundler — I usually exclude the `pagefind.js` import from bundling altogether and load it dynamically. Usually with something like

```js
import(/*webpackIgnore: true*/ '/pagefind/pagefind.js');
```

I don't know if there's a nice way to transitively target just the `/pagefind/pagefind-entry.json` import within that file. I think esbuild ignores them by default, and I haven't used *pack in a while so it's not fresh on my mind. 

Let me know if there's anything that would help from Pagefind's side. I have been wanting to publish a wrapper around the search JS as a npm package, so this might be a good prompt to do so. I need to do some research first on how to reliably make that wrapper around a dynamic import.

**Comment by pmillspaugh** [comment]
Thanks for getting back to me, @bglw! I'll try your suggestion of telling webpack to ignore the search bundle.

An npm package for the search JS would be handy, but in the meantime hopefully I'll get this working and feel more comfortable with bundlers as a result 🙂

**Comment by pmillspaugh** [comment]
Worked like a charm — thank you, @bglw! [PR updated](https://github.com/pmillspaugh/petemillspaugh.com/pull/15) with a [preview deployment](https://petemillspaugh-ev532p1nj-pmillspaugh.vercel.app/search) showcasing the snappy search. 

Now I just need to cobble together a UI and ship it, then I'll write up a blog post in case anyone else is keen on using Pagefind with Next.js.

**Comment by bglw** [comment]
Awesome! Looking forward to it — ping me when a post is out and I'll add it to the resources page 🙂

**Comment by pmillspaugh** [comment]
[Shipped](https://www.petemillspaugh.com/nextjs-search-with-pagefind). Thanks again, @bglw!

**Comment by pmillspaugh** [comment]
I made a few tweaks to my implementation and the blog post (added a section with more pagefind options and clarified pnpm `postbuild`—thanks to [@noxify](https://github.com/pmillspaugh/petemillspaugh.com/issues/17#issuecomment-1780500448)). Lmk if you have any feedback, @bglw!
