### ISSUE TITLE
Pagefind fails to install in Gitlab CI pipeline

### ISSUE THREAD

**Issue by leogaggl** [CloudCannon/pagefind#486]
I am trying to install pagefind as part of a Gitlab CI pipeline. The npm prerequisite is already installed.

```
$ npx pagefind --site public
npm ERR! cb.apply is not a function
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-10-25T02_38_19_289Z-debug.log
Install for [ 'pagefind@latest' ] failed with code 1
Cleaning up project directory and file based variables
```

Anyone have experience in running pagefind a different way? Via binary?

Thanks for the excellent work BTW! This is a great project for static sites.

**Comment by bglw** [comment]
Yep! Some discussion here: https://github.com/CloudCannon/pagefind/discussions/477#discussioncomment-7324001

Let me know if you need a further hand 🙂

**Comment by leogaggl** [comment]
Running it via the binary build works!

Maybe it's worth adding to docs somewhere that the npx install does not seem to work in those Alpine builds? 

Thanks for your quick reply!!!

**Comment by bglw** [comment]
Good idea, I'll do so 🙂
