### ISSUE TITLE
Make Pagefind available as a Rust library crate

### ISSUE THREAD

**Issue by holyjak** [CloudCannon/pagefind#487]
Hello! I currently use the Node API to index custom files ([EDN](https://github.com/edn-query-language/), in particular). It takes around 3 minutes to index 1100 files. I imagine that doing this in Rust would be much faster. Since pagefind is written in Rust, would you consider exposing a Rust API for custom indexing? Thank you!

**Comment by bglw** [comment]
👋 Hey @holyjak 

This is definitely something that could be exposed! 🙂

One note though — the 1.0.3 does have a performance issue with the API indexing files. If you give [1.0.4-beta.0](https://www.npmjs.com/package/pagefind/v/1.0.4-beta.0) an install you should see much-much-much better performance.

Sorry about that! I'll look at preparing a release soon.

**Comment by holyjak** [comment]
You were right, the 1.0.4 beta is done in 5 sec. Amazin!

**Comment by bglw** [comment]
👋 Forgot about this issue! This has been implemented in v1.3.0 :)
