### ISSUE TITLE
Feature: Add the capacity to call openai api 

### ISSUE THREAD

**Issue by MChorfa** [CloudCannon/pagefind#488]
Motivation: 
I want to be able to search on my static website and to able to generate new content from my search to augment the user experience.

Holistic Workflow: 
- Perform an initial search
- Augment the prompt template with the new searched context
- Call OpenAI API
- Display the completion with the generated content and the initial search result as a source

That way we have dynamic Retrieval Augmented Generation on static content 

Inspiration: https://www.mendable.ai/

**Comment by bglw** [comment]
👋 

This is somewhat outside of the scope of Pagefind. Any augmentation or result hydration is possible with the existing APIs. Anything beyond that is out of Pagefind's realm as a frontend library — taking OpenAI as an example, there is no context for Pagefind to integrate that wouldn't expose your API key on a public site. You'd need to host your own server to proxy those requests, and everything Pagefind needs to permit that workflow exists already 🙂
