### ISSUE TITLE
Docs: `resultTemplate` UI config option is missing

### ISSUE THREAD

**Issue by ttntm** [CloudCannon/pagefind#511]
It seems like https://github.com/CloudCannon/pagefind/blob/971186cdd062995c14d2cc2bc711b09c850d086f/pagefind_ui/modular/components/resultList.js#L31 is missing from the docs.

I would expect it to be included somewhere in the "References" section, more specifically in [Pagefind UI configuration options](https://pagefind.app/docs/ui/).

**Comment by bglw** [comment]
👋 Hey @ttntm 🙂

For now, everything under the `modular` directory is in flux — it's currently documented at https://www.npmjs.com/package/@pagefind/modular-ui.

The documentation on pagefind.app only covers the "Default UI" — which does not have a `resultTemplate` option available.

Hope that helps explain things! The API surface of the Modular UI is likely to change before being locked in and released, hence the delay in sharing that configuration. It's on the (near) roadmap 🙂

**Comment by ttntm** [comment]
Hi @bglw 👋

Thanks for answering that question so quickly. I understand and it makes sense. 

I would not have found it if it wasn't for some article out there though. It's not a game changer, but it does indeed offer a little more flexibility in the implementation compared to "just" styling the default UI.
