### ISSUE TITLE
Changing the text "clear" of the clearing button

### ISSUE THREAD

**Issue by evanescente-ondine** [CloudCannon/pagefind#577]
Hi, I'm a bit bugged by the "Clear" content of the button element, I wish I could get a X instead, or an arbitrary nice character, or an svg.
What do I need to write with "new PagefindUI(" to correct that ?
I don't know javascript.

Thanks

**Comment by nhoizey** [comment]
@evanescente-ondine you can change the labels like this:

```javascript
window.addEventListener('DOMContentLoaded', (event) => {
    new PagefindUI(
      {
        element: "#search",
        translations: {
          clear_search: "X",
        }
      });
  });
```

Other translatable strings are listed here: https://github.com/CloudCannon/pagefind/blob/main/pagefind_ui/translations/en.json

I don't think you can put an image there.

**Comment by evanescente-ondine** [comment]
ok, I'm starting to understand the pattern now. Much thanks, what a great
app.
