### ISSUE TITLE
How to pass default filter conditions to the default UI?

### ISSUE THREAD

**Issue by flyfoto** [CloudCannon/pagefind#581]
I couldn't find out how I could preset some filter conditions for a search in the default-UI.

I expected something similar to the method pagefindUi.triggerSearch(searchString) that allows to preset the search term.

Why? 
I save the current search (including filter conditions) in the URL and look for a way to reconstruct that search when opening that URL.
E.G. 
[https://fly-foto.de/luftbild/suche/?q=burg&Land=Frankreich&Jahr=2022](https://fly-foto.de/luftbild/suche/?q=burg&Land=Frankreich&Jahr=2022)

I don't want to switch from the default-UI to the JS-API.

May be this is a possible feature for the next release?

**Comment by bglw** [comment]
Yep, this is a good candidate for a feature alongside triggerSearch! I'll look into it.
