### ISSUE TITLE
[Question] Pagefind language detection at page init may be stale

### ISSUE THREAD

**Issue by gustaveWPM** [CloudCannon/pagefind#596]
Hello,

The documentation of Pagefind says:
> When Pagefind initializes in the browser it will check the same lang attribute and load the appropriate index.

https://pagefind.app/docs/multilingual/

But what happens if I have something like an i18n lib with reactive hooks, whether in React, VueJS, whatever? :/
It may change the html `lang` attribute without a page reload.

What should I do to ensure this lang attribute detection is never stale?

**Comment by bglw** [comment]
In cases where you've changed the language, you'll need to reinitialize Pagefind. You can see a similar tip for how to do that here: https://github.com/CloudCannon/pagefind/issues/593#issuecomment-2046188207

As long as the `lang` attribute is set on the html document, then re-initializing will pull the new language and load the new indexes.

**Comment by gustaveWPM** [comment]
> In cases where you've changed the language, you'll need to reinitialize Pagefind. You can see a similar tip for how to do that here: [#593 (comment)](https://github.com/CloudCannon/pagefind/issues/593#issuecomment-2046188207)
> 
> As long as the `lang` attribute is set on the html document, then re-initializing will pull the new language and load the new indexes.

Wow, thank you!
Will give it a look to this.

I think it would be a good idea to document this to show an example of which "Standard" way we should use Pagefind in this context. ^^'

**Comment by gustaveWPM** [comment]
Oh, well, I'm not using the PagefindUI.
https://github.com/Tirraa/dashboard_rtm/blob/main/src/components/hooks/usePagefind.ts

**Comment by gustaveWPM** [comment]
Update: okay, I'm dumb.
This seems to work properly.

```ts
function usePagefind(currentLocale: LanguageFlag) {
  useEffect(() => {
    async function loadPagefind() {
      try {
        // @ts-ignore generated after build
        const freshPagefind = await import(/* webpackIgnore: true */ '../pagefind/pagefind.js');
        window.pagefind = freshPagefind;
        await window.pagefind.destroy();
        await window.pagefind.init();
      } catch (error) {
        console.warn('Pagefind failed to load, search will not work');
        window.pagefind = { debouncedSearch: () => ({ results: [] }), search: () => ({ results: [] }) };
      }
    }
    loadPagefind();
  }, [currentLocale]);
}
```

Am I doing something wrong here?

**Comment by bglw** [comment]
Re-initializing should work fine — and you shouldn't need to import a freshPagefind again. 

The browser will actually de-dupe that for you, so doing another `await import` will return the exact same instance, which is why you previous example would have shown no change. 

In this case, if you have an existing `window.pagefind`, you can just do

```
await window.pagefind.destroy();
await window.pagefind.init();
```

Without importing or reassigning anything

**Comment by gustaveWPM** [comment]
> Re-initializing should work fine — and you shouldn't need to import a freshPagefind again.
> 
> The browser will actually de-dupe that for you, so doing another `await import` will return the exact same instance, which is why you previous example would have shown no change.
> 
> In this case, if you have an existing `window.pagefind`, you can just do
> 
> ```
> await window.pagefind.destroy();
> await window.pagefind.init();
> ```
> 
> Without importing or reassigning anything

Yep, it likely hits the cache.
I was just wondering if there were any on-load side-effects. Thank you!

**Comment by gustaveWPM** [comment]
It seems to be good for me now.
Should we close this issue, or should I rename it according to some potential documentation updates? @bg

**Comment by bglw** [comment]
I'll close this out and keep any documentation changes in mind when I'm next changing those files 🙂
