### ISSUE TITLE
[Feature request] Score exact name of page highly

### ISSUE THREAD

**Issue by clydebarrow** [CloudCannon/pagefind#617]
It would be nice IMHO if a search that exactly matched the name of a page would deliver that page as the top hit. E.g. searching for "I2C" would put a page called "I2C.html" at the top (without case sensitivity of course.)

**Comment by bglw** [comment]
Very much agreed!

In the interest of keeping the issues board down, I'll point you toward the two issues to subscribe to for this:

- #437 
- #532 

Any updates on this will wind up in one of those two issue threads :) 
_(and feel free to jump into either of those more more Qs or context!)_
