### ISSUE TITLE
Difference in the results by including `a` in the middle. 

### ISSUE THREAD

**Issue by shubham-padia** [CloudCannon/pagefind#627]
Thanks for this lightweight library for search :)

I'm currently prototyping an [Astro/Starlight](https://github.com/withastro/starlight) website which uses PageFind for its search. I've deployed a very rough prototype of migrating some existing documentation to https://zulip-help-center-search-starlight.netlify.app/. 

When searching for the `manage user` search query, it gives the following results which are accurate.
![image](https://github.com/CloudCannon/pagefind/assets/13910561/3b02277f-9ce3-4d1e-b863-094528ccf73f)

But, when searching for `manage a user`, the page is somehow not in the top 20 results.
![image](https://github.com/CloudCannon/pagefind/assets/13910561/91a844a3-cf86-4f95-a8bc-41e85c2bbd60)

Looking at Starlight's codebase, it looks like they are using the library as-is. Pagefind version in Starlight: `"pagefind": "^1.0.3"`.

Any help in explaining this behaviour will be appreciated, thanks!

**Comment by shubham-padia** [comment]
I've tried upgrading to pagefind v1.1.0 locally and the problem still persists.

**Comment by bglw** [comment]
Ah interesting. Yeah this does highlight an issue with the current ranking system, I'll look to improve this.

To remedy this, you should be able to crank the [termSimilarity setting](https://pagefind.app/docs/ranking/#configuring-term-similarity) way up. e.g.

```js
new PagefindUI({
    element: "#search",
    ranking: {
        termSimilarity: 10 // or 20 or 100 or 1000
    }
});
```

**Comment by shubham-padia** [comment]
Thanks for the reply! Increasing the setting made the results worse for me. In addition to that, increasing/decreasing the other settings also didn't help a lot. 

But, I removed the [stopwords](https://productresources.collibra.com/docs/collibra/latest/Content/Settings/ServicesConfiguration/co_stop-words.htm#:~:text=The%20default%20list%20of%20English,%2C%20was%2C%20will%20and%20with.) in `processTerm` of the pageFind UI and it worked fine.

**Comment by shubham-padia** [comment]
Reoping after noticing this excerpt from #48

> Reason №2 is to improve search ranking, so that searching for the editor cares more about editor than the. Removing stop words altogether is a heavy handed way of solving this, and the planned implementation of word ranking with BM25 will de-rank the the automatically without needing to put it on a list, while still keeping it in the index.

**Comment by bglw** [comment]
Ok a lot of improvement has been made in this area in [v1.5.0](https://github.com/Pagefind/pagefind/releases/tag/v1.5.0) 🙂 Still some work to do, but enough that I'll close this issue out for now.
