### ISSUE TITLE
Pagefind 1.1.0 output is not stable

### ISSUE THREAD

**Issue by sebbASF** [CloudCannon/pagefind#638]
Running pagefind 1.1.0 several times in succession generates several differently named fragment files with slightly different sizes, and the hash value in pagefind-entry.json changes.

AFAICT this did not happen with 1.0.3

It seems odd that the output should change even though the input has not.

**Comment by bglw** [comment]
Ah, I'll look into this. Likely something being output from a hashmap in arbitrary order that I should change. Thanks for the pointer!

**Comment by bglw** [comment]
Hi @sebbASF & @julbd 

As of [Pagefind v1.3.0](https://github.com/CloudCannon/pagefind/releases/tag/v1.3.0) the fragment hashes are now stable between builds 🎉

Other files will still change, such as the filter/metadata indexes _(some intended, some unintended)_. But the fragment files are the bulk of the file count and now those will not change for spurious reasons.

Let me know if you encounter any further issues 🙂
