### ISSUE TITLE
Alpine Image for Pagefind

### ISSUE THREAD

**Issue by joergklein** [CloudCannon/pagefind#640]
Is it possible to create and maintain an Alpine image for Pagefind?

**Comment by bglw** [comment]
Hey @joergklein  👋 

That isn't something I'd have the bandwidth to maintain officially — I don't currently do any image management so it wouldn't get the attention it needs.

If anyone is keen to build/maintain an unofficial image, let me know if there's something Pagefind can do to make that process easier 🙂
