### ISSUE TITLE
Configure max build file number

### ISSUE THREAD

**Issue by anoop-b** [CloudCannon/pagefind#641]
Hitting a max limit on the number of build files (20000) on cloudflare pages. 

Is there a way to configure the number of generated files?

Alternatively I'd like to explore a way to upload the generated assets to r2 or other other destinations if possible.

**Comment by bglw** [comment]
The best issue to follow for this would be #74 — though there isn't work underway on that yet.

There shouldn't be a barrier to uploading Pagefind's files to another destination. You'd just need to run Pagefind, upload those files, and then remove the index from disk before finishing so Cloudflare Pages doesn't encounter them.

**Comment by forbidden-lab** [comment]
for fragment hosted on R2 upload is real slow. 9934 fragments around 3MB in total size. Upload take 25 minutes.

**Comment by bglw** [comment]
I'll close this issue as a duplicate, but make sure to follow #74 where I'll post any updates :)
