### ISSUE TITLE
chore: update github action versions to handle node.js 16 deprecations

### ISSUE THREAD

**Issue by SKalt** [CloudCannon/pagefind#651]
The auto-merge and release GitHub workflows are currently emitting warnings about deprecated actions.

<details><summary>Excerpts from the relevant warnings</summary>

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/cache@v3, actions/setup-node@v3, actions-rs/toolchain@v1, jetli/wasm-pack-action@v0.4.0, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
>
> -- https://github.com/CloudCannon/pagefind/actions/runs/8994420084

>  Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, peter-murray/workflow-application-token-action@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
>
> -- https://github.com/CloudCannon/pagefind/actions/runs/9719697671

</summary>

**Comment by bglw** [comment]
Thanks! I'll fire out an alpha release to make sure the packaging is still working as expected.

**Comment by bglw** [comment]
https://github.com/CloudCannon/pagefind-beta/releases/tag/v1.1.1-alpha.2

<img width="249" alt="Screenshot 2024-07-17 at 1 52 04 PM" src="https://github.com/user-attachments/assets/837fc4b5-9184-4ea0-a499-dca93d445d6f">

Looks good :)
