### ISSUE TITLE
Code block HTML detected and rendered as real HTML

### ISSUE THREAD

**Issue by brycewray** [CloudCannon/pagefind#67]
Did a search today for `install Hugo`; result #19 brought up a segment of text from https://www.brycewray.com/posts/2022/07/more-tips-using-giscus/ — which, although actually a code block showing HTML, was rendered by Pagefind as **real** HTML. Here's the original code block:

```html
<details class="comments">
	<summary class="ctr pokey">
		<strong>View/hide comments</strong>
	</summary>
	<div class="giscus-comments">
		<script src="https://giscus.app/client.js"
			{{/*
			... and all your specific settings,
			which we'll skip here to save space
			*/}}
		>
		</script>
		<p class="ctr pokey sansSerif">
			Commenting by <strong><a href="https://giscus.app" rel="nofollow">giscus</a></strong>.
		</p>
	</div>
</details>
```
. . . and the attached image is how it appeared.

<img width="762" alt="HTML-from-code-block__2022-09-06-2107CDT" src="https://user-images.githubusercontent.com/14099446/188772958-df0d627a-8605-4ccb-b516-259b043f38c1.png">

I have numerous code blocks within my site, including plenty with HTML, but this is the first time one has shown up in Pagefind results as **rendered** HTML. 😄 

Not really a huge deal, but just FYI.

**Comment by bglw** [comment]
Bah, that's not very good. I presume the code blocks I tested against contained html-encoded entities, which is not the case here. 

I think there's a clear spot I can tell Pagefind to re-encode any entities before saving the content fragments. I'll have a poke 🙂

**Comment by bglw** [comment]
Apologies for the delay — this should now be fixed in https://github.com/CloudCannon/pagefind/releases/tag/v0.12.0
