### ISSUE TITLE
Wrong output path when using `--bundle` with a relative path

### ISSUE THREAD

**Issue by cipriancraciun** [CloudCannon/pagefind#68]
If one uses `pagefind` with `--bundle ./bundle --source /.../some-site`, then `./bundle` path is interpreted as relative to the `--source`, not relative to the current working directory where `pagefind` was started.

(This makes me believe that `pagefind` uses `chdir` to switch to the `--source` path, and then all other paths from the CLI that are relative are misinterpreted as relative to the `--source`.)

Perhaps a quick solution is before doing that `chdir` to resolve all CLI path arguments into absolute paths.

(Fortunately this is not a major blocking point because one can just pass absolute paths as arguments.)

**Comment by cipriancraciun** [comment]
Now I see that the `--bundle-dir` option clearly states `Where to output the search files, relative to source`.

So this is not a bug, but still quite a strange and unexpected behaviour...

**Comment by bglw** [comment]
Hi @cipriancraciun 👋 

This is something I have had a couple people hit, I can explain the reasoning:

1. The intention of Pagefind is that you're modifying a site in-place, so `bundle-dir` is denoting where in the `source` you want to add the search index
2. It makes `bundle-dir` have a clearer default of `_pagefind` rather than `source + '/_pagefind'`
3. It reduces clashes between options. 
For instance, if you have a `pagefind.yml` file containing `bundle_dir: search`, and then you run pagefind with `npx pagefind --source public`, those options will be merged and my intention was that changing your source folder doesn't require also changing the bundle dir to match.

It is slightly confusing as-is though, so maybe a good plan would be to rename the option to something more self-documenting. Open to suggestions there 🙂

**Comment by cipriancraciun** [comment]
In the end I've understood your reasoning behind the current behaviour, and it's a sensible default.

How about this minor tweak:
* add an option like `--bundle-subdir <folder-name>`;  that should be at least more suggestive, because of the `subdir` word might attract some attention;  (this option should not allow anything that starts with `/`, `./`, `../`, ends with `/.` or `/..`, or that contains `/./` or `/../`, or is equal to `.` or `..`, as it might imply that someone is misusing this flag;  perhaps more thought into corner cases would be needed;)
* add another option like `--bundle-absdir <folder-path>` that expects a path which is to be interpreted relative to the current folder;  (although `absdir` might imply absolute, that is to differentiate it from `subdir`;  it should accept also relative paths;)
* update the current `--bundle-dir` to automatically choose between `--bundle-subdir` and `--bundle-absdir` based on how the path looks like;  (for example if it fails any of the `subdir` checks, then use `absdir`;)  at the same time this option should be marked as deprecated, removed from the help, and when it's used a warning should be printed;

In think the above approach is sensible enough:  it shouldn't break the current behavior, meanwhile adding options for explicit anchoring of the bundle folder.

(The same should happen to the option in the `pagefind.yml`.)

----

About the default of changing the sources folder (by creating some files / folders in there), I don't think this is a wise approach.  When a tool says that something is a "source" I really don't expect it to go and touch it...  (In fact before reporting this bug I've tested it on my own notes site without any "fear" because it said "source";  and when I didn't find my bundle I thought perhaps the tool was broken;  only later did I check my "sources" and had to remove the bundle from there.)

Perhaps a more "neutral" name like "public-dir" (which is how most SSGs name their output folders) might make the user stop and look in the documentation to check if `pagefind` would change something in there.

**Comment by bglw** [comment]
Hi @cipriancraciun 👋 

Just dropping in to say I haven't forgotten about these suggestions 🙂 I have them tucked away for when I next make a larger breaking change to Pagefind (such as a 1.0 or 2.0 release), not that they're breaking as such but they'll be easier to document as part of a larger migration.

**Comment by cipriancraciun** [comment]
@bglw Thanks for keeping the suggestions in mind.  Looking forward for them in the next release.
