### ISSUE TITLE
Excerpts show "__PAGEFIND_ANCHOR__"

### ISSUE THREAD

**Issue by lpereira** [CloudCannon/pagefind#681]
I'm experimenting with pagefind 1.1.0, and in the [search page](https://tia.mat.br/pages/search.html) for my blog, all hits contains `__PAGEFIND_ANCHOR__a:8:...`, where `...` is the anchor name.

For instance:
![Screenshot from 2024-08-14 22-35-08](https://github.com/user-attachments/assets/77aff7b9-5223-4198-9435-9b74b9a248db)

The anchors are created like so:

```html
<h1 id="anchor-name">
<a href="#anchor-name" id="anchor-name">Anchor Name</a>
</h1>
```

I'm invoking pagefind with `pagefind --site root-directory`.

On a quick glance, it seems like there's some code to remove this substring in `pagefind/src/fossick/mod.rs`, but it doesn't seem to work in all cases. I'm having issues building from source (`include_bytes!` macro invocation failing to include things in the vendored directory; I'll investigate the root cause later), otherwise I'd look into this. I'm happy, however, to provide any additional information that might be required to reproduce this issue.

**Comment by bglw** [comment]
Hey @lpereira 👋 

Thanks for the report! That's not great, that token shouldn't be leaking out anywhere 🙈 I'll get this test case into an integration test stat and figure out what's afoot.

> I'm having issues building from source

I should really get onto providing better build scripts — sorry about that! The things that need to vendor before building Pagefind are detailed here: https://github.com/CloudCannon/pagefind/blob/main/CONTRIBUTING.md#building-the-supporting-packages

**Comment by bglw** [comment]
Update: Didn't have to look far! Somehow these slipped through never being handled when inside metadata. Will fix.

**Comment by lpereira** [comment]
I ended up fixing the thing that generates the HTML too, so that it doesn't generate multiple tags with the same ids, which was wrong to begin with.  (With your fix, this shouldn't happen anymore either.)

Thank you for the fast turnaround!

**Comment by bglw** [comment]
Awesome! I need to fix up our CI 🙈 but I'll get this released soon :)
