### ISSUE TITLE
HTML parse encountered an error: ParsingAmbiguity

### ISSUE THREAD

**Issue by dprothero** [CloudCannon/pagefind#69]
I'm using [Docusaurus](https://docusaurus.io/), a React-based SSR for documentation sites. On my site, I'm getting the following:

```bash
❯ npx -y pagefind --source build --serve

Running Pagefind v0.8.0 (Extended)
Running from: "/Users/dprothero/Projects/internal-product-docs"
Source:       "build"
Bundle Directory:  "_pagefind"

[Walking source directory]
Found 337 files matching **/*.{html}

[Parsing files]
thread 'main' panicked at 'HTML parse encountered an error: ParsingAmbiguity(
    ParsingAmbiguityError {
        on_tag_name: "style",
    },
)', /Users/runner/work/pagefind/pagefind/pagefind/src/fossick/mod.rs:62:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

When I try pagefind on the stock Docusaurus template, it works fine, so this is clearly something with my site, but the error does not provide enough information to diagnose the problem.

**Comment by bglw** [comment]
Oh no, this is the first I've seen the parser crash. Do you have any public code you can share that triggers the error?

I can fix it up so that it doesn't bail out in this case and instead logs any pages it wasn't able to index

**Comment by dprothero** [comment]
It's a private site, so I can't create a reproducable case. So, yeah, capturing the error and adding better logging is the way to go and then I'm happy to help find the problem and see if I can't create a reproducible case I can post here.

**Comment by bglw** [comment]
Sweet as no worries, I'll include that in the next release

**Comment by bglw** [comment]
@dprothero I have snuck out [Pagefind v0.8.1](https://github.com/CloudCannon/pagefind/releases/tag/v0.8.1) with improved handling here. Pages that hit this parsing error will be skipped and the rest of the site will be indexed. I'm also passing along a better summary of the error from lol-html, which will look something like:

> The parser has encountered a text content tag (`<style>`) in the context where it is ambiguous whether this tag should be ignored or not. And, thus, is is unclear is consequent content should be parsed as raw text or HTML markup.  
> This error occurs due to the limited capabilities of the streaming parsing. However, almost all of the cases of this error are caused by a non-conforming markup (e.g. a `<script>` element in `<select>` element).

This should track down which pages this is occurring on. It doesn't look like I will be able to improve the handling of this error, so hopefully the incoming HTML can be tweaked if the problematic pages are needed for search.

Let me know if this all works — curious to see what the problematic HTML was.

**Comment by bglw** [comment]
Interesting! I didn't change the parsing itself, and in fact added a test that explicitly checks for an error message in this case: https://github.com/CloudCannon/pagefind/blob/b0ba4537c7cc65a97f49235bc6de9f8323b64799/pagefind/features/errors.feature#L15-L22

So it looks like it's fixed on your end _(maybe in its previous run it indexed some intermediary Docusaurus file)_. Let me know if it reoccurs, but otherwise — hooray! 🎉

**Comment by jdevalk** [comment]
@dprothero any chance you can describe somewhere what you did to make docusaurus work with pagefind? :)
