### ISSUE TITLE
Implement OR filter

### ISSUE THREAD

**Issue by bglw** [CloudCannon/pagefind#7]
Pagefind supports filtering with multiple values:

```
let search = await pagefind.search("Cat", {
  filters: {
    color: ["Tabby", "Orange"]
  }
});
```

But currently only implements an `AND` filter, i.e. cats that are `Tabby` **and** `Orange`. This boolean logic should be expanded.

Once indexes are loaded, searching is extremely fast, so this could be achieved by running a `Tabby` search followed by an `Orange` search and smooshing the results together.

**Comment by bglw** [comment]
Copying context from @tenmozes in #195:

---

> 
> Hey, thank you for an awesome project
> 
> I have two questions regarding filters 
> 1. When I choose one filter, the number of search result for other shows 0 match  
> 2. Is it any way to change from checkbox to radio, in other words is any way to use OR logic instead of AND when you choose multiple filters? 
> 
> Legend:
> Image 0 - all is fine
> Image 1 - one filter is active
> Image 2 - two filters are active
> 
> <img width="1095" alt="Screenshot 2023-01-13 at 7 51 32 PM" src="https://user-images.githubusercontent.com/1381404/212397103-c48abd1c-05d1-493d-8fb8-af1d9f7eecc4.png">
> <img width="1064" alt="Screenshot 2023-01-13 at 7 48 48 PM" src="https://user-images.githubusercontent.com/1381404/212397116-1de45706-c9e6-4287-b906-50eb1f0bd2f9.png">
> <img width="1137" alt="Screenshot 2023-01-13 at 7 50 21 PM" src="https://user-images.githubusercontent.com/1381404/212397128-c1ed2fa3-e413-4897-9942-fb5cb0a08d58.png">
>

**Comment by bglw** [comment]
Good news — this has landed in Pagefind v1.0.0! 

See the full release notes here: https://github.com/CloudCannon/pagefind/releases/tag/v1.0.0 💙

This release doesn't yet bring the feature to the UI modules, but all the machinery is in place to execute these queries directly with the JS API. 

Open an issue if you have any specific UI needs for this!

**Comment by tenmozes** [comment]
Amazing, let me try :) thank you

**Comment by tenmozes** [comment]
@bglw by any change are you going to add this functionality to pagefind UI? if yes is there any milestone 
thank you!

**Comment by tenmozes** [comment]
the most simple configuration for setting up a function to match filter (any in my case) and how to display filter (totalFilters in my case) would solve my request completely

let me know if this is impossible with Pagefind UI flow and i need to build UI using API
