### ISSUE TITLE
How to run the integration tests locally

### ISSUE THREAD

**Issue by tenax66** [CloudCannon/pagefind#714]
Hi, I’m new here. Thank you for the amazing software!

I have a question about the integration tests. In `CONTRIBUTING.md`, it says:

```
To run the test suite, from the pagefind directory you can run cargo test for unit tests, or the ./test.sh script for the integration suite.
```

However, due to the change of test tool from humane to toolproof, `/test.sh` script doesn't seem to be working now.

How can I run the tests locally? Is running `./test_ci.sh` locally the expected way?

**Comment by bglw** [comment]
Hi @tenax66 👋 

Thanks for pointing that out! I have updated the contributing guide to match the latest setup.

I have also added a `./test_interactive.sh` script which is the best avenue to run tests locally.

Let me know if you have any other questions! 🙂
