### ISSUE TITLE
UI: Add `data-pagefind-meta` attribute on repeatable UX elements

### ISSUE THREAD

**Issue by regisphilibert** [CloudCannon/pagefind#742]
Currently it's impossible to CSS target a result tag based on the meta it holds as its produced html is simply:

```html
<li class="pagefind-ui__result-tag svelte-xxxx">Genre: Litterature</li>
```

By adding a simple attribute to it, it would allow users to style them differently based on the meta. 

The following would enable CSS targeting for repeatable elements such as result tags.

```html
<li class="pagefind-ui__result-tag svelte-xxxx" data-pagefind-meta="Genre">Genre: Litterature</li>
```

This could also be applied to

- `. pagefind-ui__filter-block`
- Other repeatable elements I'm not aware of :)

**Comment by bglw** [comment]
Great idea! Will do.

**Comment by bglw** [comment]
👋 @regisphilibert 

This has landed in [Pagefind v1.3.0](https://github.com/CloudCannon/pagefind/releases/tag/v1.3.0) 🎉

I have only added the attribute for metadata for now — but open another issue if you have any need for it on the filtering and we can hash out what needs an attribute and where 🙂

**Comment by regisphilibert** [comment]
Tanks @bglw! This has been super useful to made this search more inline with project's design with only a few line of css!

![Capture d’écran, le 2024-12-18 à 11 33 20](https://github.com/user-attachments/assets/785f420b-ae5e-4bfe-a3c9-aa69d06c3734)

**Comment by bglw** [comment]
Very nice 😍
