### ISSUE TITLE
Configurable logging levels

### ISSUE THREAD

**Issue by delucis** [CloudCannon/pagefind#745]
Pagefind currently supports a [`--verbose`](https://pagefind.app/docs/config-options/#verbose) flag to enable _more_ output while running, but doesn’t offer other logging levels to _reduce_ output. This is controlled via this match expression which has `Standard` and `Verbose` levels:

https://github.com/CloudCannon/pagefind/blob/596a56e9f35798742ed7023673e69cfec57395e6/pagefind/src/logging.rs#L115-L118

It would be great to have some more control over this as a user. I’m personally looking for an “errors-only” mode, but I guess “silent” and “warnings and above” are also common options in loggers.

**Comment by bglw** [comment]
Hey hey @delucis 👋 

This has landed in [Pagefind v1.3.0](https://github.com/CloudCannon/pagefind/releases/tag/v1.3.0) 🎉

You now have `--quiet` and `--silent` to choose from.

**Comment by delucis** [comment]
Lovely stuff! Thank you muchly @bglw 💖
