### ISSUE TITLE
Changed tag removes post from index

### ISSUE THREAD

**Issue by TechLifeWeb** [CloudCannon/pagefind#746]
Trying out Pagefind to implement search on my 11ty site and ran into this issue. If all code is exactly the same and the post has a tag "article" it is included in the index. If all I do is change the tag to "note" it isn't included. Comparing sources shows the only difference on the page is the text of the tag. Can't seem to figure out how to get "note" posts into the index.  Any ideas about what might be going on and how to fix it?

**Comment by bglw** [comment]
Ah, just noticed this here! Have replied on Mastodon, feel free to pick up the convo here or there 🙂

**Comment by TechLifeWeb** [comment]
Turns out the SVG that I use as an image to show the kind of note didn't have a closing tag. Once I fixed that, everything shows up in the index as expected.
