### ISSUE TITLE
Filtering on zero results returns all results for a filter

### ISSUE THREAD

**Issue by kenmorse** [CloudCannon/pagefind#84]
I'm not sure if this is an issue with Pagefind, or rather my understanding of how Pagefind filters work.

I tend to think of filters as showing **less** information than with no filtering at all, but I'm not seeing that behavior with Pagefind v0.8.1.

To see this, go to the [Pagefind docs page](https://pagefind.app/), and enter this into the search field:

`xzzzx` (or any string where you don't expect to find any results).

As expected, Pagefind shows **No results for xzzzx**. Now click any one of the filters and see that you'll get some number of results:

* Indexing (4)
* Installing (3)
* Notes (1)
* Searching (4)

I see this behavior using the Pagefind JS API as well, where a filter will return results with the same search that produces no results when a filter is not applied.

Is that expected behavior?

**Comment by bglw** [comment]
Hello @kenmorse!

This is definitely a bug 🙂 I need to tidy up the logic for search misses — currently a search word with no results effectively gets dropped from the query, which is why combining it with a filter returns the result for just that filter. I'll get this fixed up 👍

**Comment by kenmorse** [comment]
Thanks @bglw! 

In the meantime, I think a workaround for using the API could be to search first without filters, and then only if results are returned search again with filters. Pagefind is so fast that I don't think it will be an issue.

**Comment by bglw** [comment]
Hello! This is fixed in the [Pagefind v0.9.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.9.0) release 🎉
