### ISSUE TITLE
Line-breaks ignored

### ISSUE THREAD

**Issue by psaikido** [CloudCannon/pagefind#91]
I'm seeing a behaviour where line-breaks in hugo markdown files are ignored such that the html:
"annihilating into"
<br>
"cerulean blue"

--a search for "cerulean" fails but a search for "intocerulean" succeeds.

Here's the example in the wild - https://hugle.uk/hk/bucket/ink/

**Comment by bglw** [comment]
Oh, that is an issue! I'll get that fixed up

**Comment by bglw** [comment]
Hello! This is fixed in the [Pagefind v0.9.0](https://github.com/CloudCannon/pagefind/releases/tag/v0.9.0) release 🎉
